Two sync loop experimental solution to decrypt push notifications
vector-im/element-x-ios pull request #1082
Opened 2023-06-14 09:21 UTC by Velin92

This is using an external matrix rust sdk experimental branch, not merged yet in main, so it will likely fail to compile on CI for now.

The idea is to use the notification sync (which I feel it should be renamed to encryption or decryption sync) to actually update the keys.

The sync runs both in the main app and in the NSE, we can now wait for the notification to be fully decrypted (we wait for about 10 seconds at most for now but it takes way less) before showing it to the user.

This requires to not use all common extensions but remove e2ee and toDeviceEvents from the normal sync, since the notification sync does that job instead.

2023-06-14 15:49 UTC, alfogrillo commented on ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
> +        navigationStackCoordinator.popToRoot(animated: animated)
Had the same problem with animations and fixed it differently [here](https://github.com/vector-im/element-x-ios/commit/003085aa57799afdc5095b5be94bdff446f485d2). 
Not sure what's best. 
If we go with your fix, we may want to add a comment to highlight the fact that lines shouldn't be inverted again. 
Also worth checking what's happening on iPad after this change.

2023-06-15 08:40 UTC, Velin92 commented on ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
> +        navigationStackCoordinator.popToRoot(animated: animated)
Actually now that I think about this, since the invite screen on the iPad lives in the master and not in the details of the iPad, maybe we should not dismiss the room at all? Maybe we should not touch the state of the room flow coordinator

2023-06-15 09:13 UTC, Velin92 commented on ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
> +        navigationStackCoordinator.popToRoot(animated: animated)
I think we should only clear the route if we are on iPhone and keep it as it is on iPad, WDYT?

2023-06-15 13:55 UTC, alfogrillo commented on ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
> +        navigationStackCoordinator.popToRoot(animated: animated)
(discussed privately)

2023-06-19 09:39 UTC, stefanceriu reviewed
Left some comments inline but it looks good to me 👍

2023-06-19 09:39 UTC, stefanceriu commented on NSE/Sources/Other/NSEUserSession.swift
> +    private var encryptionSync: EncryptionSync!
Can we call this `encryptionSyncService` or something else along those lines?

2023-06-19 09:39 UTC, stefanceriu commented on NSE/Sources/NotificationServiceExtension.swift
> +            } while itemProxy.isEncrypted && date.timeIntervalSinceNow < 10
Probably worth leaving a warning here

2023-06-19 09:39 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
>                                                                                 // This state function is wrong but it's not used
What's this about? 🤔

2023-06-19 09:39 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
>                                                                                 // This state function is wrong but it's not used
Also, I fixed this here https://github.com/vector-im/element-x-ios/pull/1109

2023-06-19 09:39 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +private class ConcreteEncryptionSyncListener: EncryptionSyncListener {
I tried going for block based listeners for these (see the end of the file) maybe we should do the same here

2023-06-19 09:39 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +            MXLog.info("Encryption sync is already configured")
I would fatalError here, no reason why it should be configured twice

2023-06-19 09:39 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +            try encryptionSync = client.mainEncryptionSync(id: "Main App", listener: listener, withLock: true)
I was expecting these services to be similar, why doesn't encryptionSync return a taskHandle? 🤔

2023-06-19 09:58 UTC, stefanceriu commented on NSE/Sources/NotificationServiceExtension.swift
> +            } while itemProxy.isEncrypted && date.timeIntervalSinceNow < 10
Ah right, cool cool 👍

2023-06-19 10:15 UTC, Velin92 commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +private class ConcreteEncryptionSyncListener: EncryptionSyncListener {
Oh yeah I like this, and I can reuse it for NSE too.

2023-06-19 10:46 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +            MXLog.info("Encryption sync is already configured")
I personally believe we should crash as soon as we encounter unexpected states. Crashes are a lot easier to track down and people generally report them more often.

2023-06-19 10:46 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +            try encryptionSync = client.mainEncryptionSync(id: "Main App", listener: listener, withLock: true)
Alrighty ¯\_(ツ)_/¯

2023-06-19 10:49 UTC, Velin92 commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +            MXLog.info("Encryption sync is already configured")
Okay actually I refactored the code, now the room list api and the encryption sync will always work together, so I can use the fatal error now

2023-06-21 09:16 UTC, stefanceriu requested changes
I'm worried about isSyncing and merging together the 2 loops, otherwise it looks good to me 👍

2023-06-21 09:16 UTC, stefanceriu commented on ElementX/Sources/Application/AppCoordinator.swift
> +        userSession?.clientProxy.stopSync()
👍

2023-06-21 09:16 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +                MXLog.info("Encryption Sync did terminate for user: \(self?.userID ?? "unknown")")
This is a tad weird, is the listener only good for knowing when the encryptionSync stopped? 🤔

2023-06-21 09:16 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +        guard !isSyncing else { return }
I believe this will be a problem if the room list loop fails (for whatever reason) and we try to restart it. The encryption sync will still be running and it will return early without actually restarting it.

2023-06-22 08:30 UTC, Velin92 commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +                MXLog.info("Encryption Sync did terminate for user: \(self?.userID ?? "unknown")")
yeah, and it can either stop because we are stopping it, or maybe because there is no connection or other issues.
Benjamin wants to introduce a TerminationReason enum in the future.

2023-06-22 08:35 UTC, Velin92 commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +        guard !isSyncing else { return }
however now isSyncing is based on:
`roomListSyncTaskHandle != nil && isEncryptionSyncing`

So the sync to be seen as really running, both of them need to be running at the same time.
So if the room list has failed the start function is going to recreate another encryption sync which is okay because it will have the same identifier, so it will still keep the previous lock.

2023-06-22 08:39 UTC, Velin92 commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +        guard !isSyncing else { return }
otherwise we could create `startRoomListSync()` and a `stopRoomListSync()` and a isRoomListSyncing flag and use those instead to restart the room list sync in the termination cases (essentially use the same pattern we are using now for the encryption sync but for the room list sync, let me know if you prefer this solution)

2023-06-22 09:23 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +        guard !isSyncing else { return }
> the start function is going to recreate another encryption sync

Well that won't happen because there's an check in there for `guard !isSyncing else { return }`

I'm happy to ignore `&& isEncryptionSyncing` in `isSyncing` if you thing that's going to work properly.

2023-06-22 09:24 UTC, stefanceriu approved these changes

2023-06-22 17:23 UTC, merged