Add analytics tracking for room creation
vector-im/element-x-ios pull request #1100
Opened 2023-06-17 07:13 UTC by Johennes

2023-06-17 07:16 UTC, Johennes commented
CC @giomfo because I think you might have had this on your list, too.

2023-06-19 09:21 UTC, pixlwave requested changes
Nice, its good to see PostHog starting to be used!

2023-06-19 09:21 UTC, pixlwave commented on ElementX/Sources/Services/Analytics/Analytics.swift
> +    func capture(event: AnalyticsEventProtocol) {
Please can we keep this private, instead adding public methods for tracking events like we do on EI:
[trackCreatedRoom](https://github.com/vector-im/element-ios/blob/2831265badf17c77f64e228b5372beb150d8050a/Riot/Modules/Analytics/Analytics.swift#L363)

This has the advantage of not needing to import AnalyticsEvents everywhere we're going to track things so it should be easier for forks to customise analytics with different schemas.

2023-06-19 11:12 UTC, Johennes commented on ElementX/Sources/Services/Analytics/Analytics.swift
> +    func capture(event: AnalyticsEventProtocol) {
Ah ok. Was already wondering what the additional abstraction layer in the old app was good for. Makes sense and have changed.

2023-06-19 12:34 UTC, pixlwave approved these changes
LGTM 😎

2023-06-19 12:35 UTC, pixlwave commented on ElementX/Sources/Services/Analytics/Analytics.swift
> +    func capture(event: AnalyticsEventProtocol) {
Super thanks

2023-06-19 12:35 UTC, merged