Add a "Mute" shortcut icon and a "Notifications" section in the room details screen
vector-im/element-x-ios pull request #1318
Opened 2023-07-12 15:23 UTC by nimau

This PR implements: #986, #1002 

It adds a "Mute/Unmute" shortcut button to `RoomDetailsScreen` and a new `Notifications` section displaying whether the mode is the default or a custom mode.

Note: the shortcut and notifications section are only displayed if the `notificationSettingsEnabled` feature flag is enabled.

In this PR, the new `Notifications` section is clickable, but the screen for editing the notification settings for a room will be implemented in a later PR.

With the feature flag enabled:
<img src="https://github.com/vector-im/element-x-ios/assets/4334885/2a7ea075-262d-4a80-a2f5-06a36bd762f4" width=25% height=25%>
<img src="https://github.com/vector-im/element-x-ios/assets/4334885/c4688fae-cc69-4ed9-aabd-534c9a0b699c" width=25% height=25%>

With the feature flag disabled:
<img src="https://github.com/vector-im/element-x-ios/assets/4334885/a1f7df5c-d786-4a73-ba17-04075ed14b9c"  width=25% height=25%>

2023-07-12 15:49 UTC, Velin92 commented on ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
> +    private func headerSectionShortcuts() -> some View {
would make this a computed var headerSectionShortcuts: some View

2023-07-12 15:54 UTC, Velin92 commented on ElementX/Sources/Services/NotificationSettings/NotificationSettingsProxy.swift
> +        try await notificationSettings.unmuteRoom(roomId: room.id, isEncrypted: room.isEncrypted, membersCount: UInt64(room.activeMembersCount))
same as the comment above

2023-07-12 15:55 UTC, Velin92 commented on ElementX/Sources/Services/NotificationSettings/NotificationSettingsProxy.swift
> +        try await notificationSettings.restoreDefaultRoomNotificationMode(roomId: room.id)
same as the comment above for roomID, not sure for the background task, is this a possible user initiated call?

2023-07-12 15:55 UTC, Velin92 commented on ElementX/Sources/Services/NotificationSettings/NotificationSettingsProxy.swift
> +        try await notificationSettings.setRoomMentionEnabled(enabled: enabled)
as above

2023-07-12 15:55 UTC, Velin92 commented on ElementX/Sources/Services/NotificationSettings/NotificationSettingsProxy.swift
> +        try await notificationSettings.setUserMentionEnabled(enabled: enabled)
as above

2023-07-12 15:56 UTC, Velin92 commented on ElementX/Sources/Services/NotificationSettings/NotificationSettingsProxy.swift
> +        try await notificationSettings.setCallEnabled(enabled: enabled)
as above

2023-07-12 15:57 UTC, Velin92 requested changes
Very good, I would just change the SettingsProxy to use simpler signatures with just roomIDs instead of entire ProxyProtocols and would also incude a background task for user initiated changes.

2023-07-13 08:42 UTC, nimau commented on ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
> +    private func headerSectionShortcuts() -> some View {
Oh yes, of course!

2023-07-13 08:45 UTC, nimau commented on ElementX/Sources/Services/NotificationSettings/NotificationSettingsProxy.swift
> +        try await notificationSettings.setRoomNotificationMode(roomId: room.id, mode: mode)
Nice point, I've updated so any user initiated operation is now starting a background task.
Also I removed the `RoomProxyProtocol` from those methods signature to keep a 1:1 mapping with the SDK.

2023-07-13 08:47 UTC, nimau commented on ElementX/Sources/Services/NotificationSettings/NotificationSettingsProxy.swift
> +        try await notificationSettings.restoreDefaultRoomNotificationMode(roomId: room.id)
Yes, this is a user initiated call so I added a background task.

2023-07-13 09:31 UTC, Velin92 approved these changes

2023-07-13 10:37 UTC, Velin92 approved these changes
LGTM!

2023-07-13 17:27 UTC, Velin92 commented on UnitTests/Sources/NotificationManager/NotificationManagerTests.swift
> +        try await Task.sleep(for: .microseconds(500))
oh yeah that's the issue, microseconds are probably not enough, we probably need milliseconds.
I would say 10 milliseconds should be fine.

2023-07-13 17:34 UTC, Velin92 commented on UnitTests/Sources/RoomDetailsViewModelTests.swift
> +            .filter(\.isError)
I would prefer first(where:) instead of chaining a filter + first

2023-07-14 08:55 UTC, nimau commented on UnitTests/Sources/NotificationManager/NotificationManagerTests.swift
> +        try await Task.sleep(for: .microseconds(500))
I've rebased as this has already been fixed

2023-07-14 08:55 UTC, nimau commented on UnitTests/Sources/RoomDetailsViewModelTests.swift
> +            .filter(\.isError)
Oh yes of course

2023-07-14 09:43 UTC, merged