Proof of concept login via OIDC.
vector-im/element-x-ios pull request #145
Opened 2022-07-26 17:03 UTC by pixlwave

The implementation uses AppAuth-iOS in the app to negotiate with the OIDC server and ignores the refresh token so the login will only work for a short amount of time.

There's currently an issue where the Rust runtime crashes when starting sync if you have an expired token - the app has no way to recover from this, so it is a good idea to logout within 5-minutes of logging in.

2022-07-27 10:03 UTC, stefanceriu requested changes
Just a few comments inline 👍

2022-07-27 10:03 UTC, stefanceriu commented on ElementX/Sources/Services/Authentication/OIDCService.swift
> +            self.session = OIDAuthorizationService.present(request, externalUserAgent: userAgent) { response, error in
We could do the same thing we did for kingfisher and move this continuation to an extension on OID.

2022-07-27 10:03 UTC, stefanceriu commented on ElementX/Sources/Services/Authentication/OIDCService.swift
> +                                  userAgent: OIDExternalUserAgent) async throws -> OIDAuthorizationResponse {
We should probably use Result here instead of throwing exceptions.

2022-07-27 10:39 UTC, pixlwave commented on ElementX/Sources/Services/Authentication/AuthenticationServiceProxy.swift
> +            let oidcUserAgent = oidcUserAgent,
Derp, makes much more sense to me 👍

2022-07-27 10:50 UTC, pixlwave commented on ElementX/Sources/Services/Authentication/OIDCService.swift
> +                                  userAgent: OIDExternalUserAgent) async throws -> OIDAuthorizationResponse {
For this temporary implementation, it doesn't seem worth the effort. Especially as it will make the `loginWithOIDC` method grow in the auth service proxy.

2022-07-27 10:57 UTC, pixlwave commented on ElementX/Sources/Services/Authentication/AuthenticationServiceProxy.swift
> +    private func generateDeviceID() -> String {
This is all temporary, when rust has OIDC we should never need to generate a device ID.

2022-07-28 08:12 UTC, stefanceriu approved these changes

2022-07-28 08:28 UTC, merged