Avatar Bloom View in home screen navigation bar
vector-im/element-x-ios pull request #1630
Opened 2023-09-05 09:06 UTC by Velin92

WIP
Needs to be approved by compound design first.

2023-09-07 17:41 UTC, janogarcia requested changes
Thanks for the demos and test build, Mauro! We're getting super close to the final implementation.

- Blending modes: We updated the values as follows. Light theme has a `Hard Light` bottom layer @ 20% opacity, and a top `Color` layer @ 80% opacity. Dark theme has a `Exclusion` bottom layer @ 50% opacity, and a top `Color` layer @ 20% opacity
- Soft edge mask: We settled 40px/pt for the linear gradient height.
- Collapsed navigation bar: The bloom shouldn't change its position, if possible, and just be cropped instead (e.g., [behavior on Android](https://matrix.to/#/!tuoNvqSfUFMgFtnlKz:matrix.org/$AB-j8TtBuWRQtizUnJH_dvkz_JCWKTVTm9uHE7Fvb_8?via=element.io&via=matrix.org&via=jki.re)).

2023-09-08 09:50 UTC, janogarcia requested changes
Based on the latest screenshots that @Velin92 just shared over DM.

- When the Navigation Bar is not collapsed, the linear gradient mask for the "soft edge" effect seems to not be properly placed, there's a small visible gap.
- When the Navigation Bar is collapsed, we don't have to render the linear gradient mask for the "soft edge" effect.
- We should restore the hairline border on the Navigation Bar bottom.

2023-09-08 10:11 UTC, pixlwave commented on ElementX/Sources/Screens/HomeScreen/View/HomeScreen.swift
> +        let hostingController = UIHostingController(rootView: bloom)
Might be nice to call this `bloomController` now there's a `gradientController`

2023-09-08 13:51 UTC, pixlwave approved these changes
👏👏👏

2023-09-08 13:51 UTC, pixlwave commented on ElementX/Sources/Other/ScrollViewAdapter.swift
> +    var scrollViewIsAtTopEdgePublisher: CurrentValuePublisher<Bool, Never> {
Looking at the ones above, this would be more aligned naming
```suggestion
    private let isAtTopEdgeSubject: CurrentValueSubject<Bool, Never> = .init(false)
    var isAtTopEdge: CurrentValuePublisher<Bool, Never> {
```

2023-09-08 13:51 UTC, pixlwave commented on ElementX/Sources/Other/ScrollViewAdapter.swift
> +        let contentInsetOffset = scrollView.contentOffset.y + scrollView.contentInset.top
Bah, I finally realised the ordering that makes sense 😅
```suggestion
        let insetContentOffset = scrollView.contentOffset.y + scrollView.contentInset.top
```

2023-09-08 13:51 UTC, pixlwave commented on ElementX/Sources/Screens/HomeScreen/View/HomeScreen.swift
> +    @Environment(\.colorScheme) private var colorScheme
This one is unused now :)

2023-09-08 13:51 UTC, pixlwave commented on ElementX/Sources/Screens/HomeScreen/View/HomeScreen.swift
> +    @State private var bloomView: UIView?
Maybe useful to group these together now there is so many of them 🙃
```suggestion
    
    // Bloom components
    @State private var bloomView: UIView?
```

2023-09-08 13:51 UTC, pixlwave commented on ElementX/Sources/Screens/HomeScreen/View/HomeScreen.swift
> +                    startPoint: .leading, endPoint: .trailing)
Should probably be like this (I thought SwiftFormat would be upset in some way about this).
```suggestion
                LinearGradient(stops: [.init(color: .white, location: 0.75), .init(color: .clear, location: 1.0)],
                               startPoint: .leading,
                               endPoint: .trailing)
```

2023-09-08 13:51 UTC, pixlwave commented on ElementX/Sources/Screens/HomeScreen/View/HomeScreen.swift
> +    private func setBloomView(controller: UIViewController) {
Might be a bit clearer as `set` could be interpreted that `controller` is the bloom view controller.
```suggestion
    private func makeBloomView(controller: UIViewController) {
```

2023-09-08 14:45 UTC, merged