implement emotes (/me)
vector-im/element-x-ios pull request #1841
Opened 2023-10-01 23:52 UTC by ara4n

requires https://github.com/matrix-org/matrix-rust-sdk/pull/2648

### Pull Request Checklist

- [x] I read the [contributing guide](https://github.com/vector-im/element-ios/blob/develop/CONTRIBUTING.md)
- [ ] Pull request contains a [changelog file](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#changelog) in ./changelog.d

2023-10-02 00:16 UTC, ara4n commented
How do I make the tests run against the right sdk branch name? (EW would at least automatically try to build against the branch of the same name in the SDK...)

2023-10-02 05:58 UTC, stefanceriu requested changes
Left comments inline for a couple of small tweaks that need to happen. Otherwise looks sensible to me.

@Velin92 you were going to look into user suggestions this week. They should probably be based on `CompletionSuggestion` from the old codebase which also supports slash commands so please take this PR under your wing.

2023-10-02 05:58 UTC, stefanceriu commented on ElementX/Sources/Services/Room/RoomProxy.swift
> +    func checkEmote(body: inout String, htmlBody: inout String?) -> Bool {
This needs to be private and moved down to the right section but also the name is off as it doesn't just "check" but also modifies the original strings. 
I would split it into 2 clear methods `checkIsEmote` and `buildEmoteContent`. I'm not a fan of `inout` parameters so let's make `buildEmoteContent` return a tuple.

2023-10-02 05:58 UTC, stefanceriu commented on ElementX/Sources/Services/Room/RoomProxy.swift
> +        let emote: Bool = checkEmote(body: &body, htmlBody: &htmlBody)
Let's call this `isEmote`

2023-10-02 05:58 UTC, stefanceriu commented on ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
> +                if ServiceLocator.shared.settings.richTextEditorEnabled, let formattedBodyHTMLString = emoteItem.formattedBodyHTMLString {
Are you sure we want to give users the option to edit the original `/me`? What happens if they just delete it? Would the event turn into a plain room message text? 🤔

2023-10-02 06:25 UTC, ara4n commented on ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
> +                if ServiceLocator.shared.settings.richTextEditorEnabled, let formattedBodyHTMLString = emoteItem.formattedBodyHTMLString {
yup, which is desirable, so you can change whether you meant to do a /me or not.

2023-10-02 08:27 UTC, stefanceriu commented
> run against the right sdk branch name?

There is nothing like that atm. We agreed to look into building the sdk on the CI after the next release and this can very well be a part of that work.

2023-10-02 09:18 UTC, manuroe commented
> > run against the right sdk branch name?
> 
> There is nothing like that atm. We agreed to look into building the sdk on the CI after the next release and this can very well be a part of that work.

We will also need to improve the infra. GH action runners are slow to build the SDK bindings. They take [4h](https://github.com/matrix-org/matrix-rust-components-kotlin/actions/runs/6312986182) to build them for Android. This would be way too long to validate a PR on EAX or EIX.

2023-10-02 11:24 UTC, ara4n commented
ptal

2023-10-03 08:47 UTC, Velin92 commented on ElementX/Sources/Services/Room/RoomProxy.swift
> +            }
Can we a private func that does this? I also see that this code is quite similiar to the code below, so maybe we can actually have 1 single function and avoid replication?

2023-10-03 08:48 UTC, Velin92 commented on ElementX/Sources/Services/Room/RoomProxy.swift
> +            }
As I said in the comment above, this is replicated and we can extract it into a function.

2023-10-03 12:32 UTC, Velin92 approved these changes

2023-10-03 13:17 UTC, stefanceriu approved these changes

2023-10-03 13:17 UTC, merged