Add voice message playback from the timeline
vector-im/element-x-ios pull request #1844
Opened 2023-10-02 07:51 UTC by nimau

This PR adds the ability to listen to voice messages from a timeline item ( (part of the [Voice Messages](https://github.com/vector-im/element-meta/issues/2057) feature)

Here is a brief explanation of this implementation:
- When a playback action is sent to the `RoomTimelineController`, an `AudioPlayer` is attached (if necessary) to the corresponding timeline item via its `AudioPlayerState`
- There is only one `AudioPlayer` instantiated, and its state is restored when it is attached.
- A basic cache `AudioCacheManager` has been implemented, which is currently cleared when the `MediaPlayerProvider` instance is deinitialised (.i.e when we exit the room screen). This will probably change when the recording feature is implemented.
- This cache can contain the ogg file and its converted version (m4a), and these temporary files use the media source url as identifier.

In order not to affect performance when rendering the timeline, voice messages are not pre-loaded (and no conversion to _m4a_ is performed until we need it).
For a 5-minute voice message, the time taken to convert it the first time is around 1 second.

2023-10-02 14:37 UTC, stefanceriu requested changes

2023-10-02 14:37 UTC, stefanceriu commented on ElementX/Sources/Services/Audio/AudioPlayerProtocol.swift
> +    var callbacks: AnyPublisher<AudioPlayerCallback, Never> { get }
I think we started calling these `actions` everywhere (or almost everywhere)

2023-10-02 14:37 UTC, stefanceriu commented on ElementX/Sources/Services/Media/Provider/MediaPlayerProvider.swift
> +    private var audioCacheManager = AudioCacheManager()
This should be injected, no?

2023-10-02 14:37 UTC, stefanceriu commented on ElementX/Sources/Services/Media/Provider/MediaPlayerProvider.swift
> +import UniformTypeIdentifiers
I guess you imported this so you can check that `/audio` but it's not used atm

2023-10-02 14:37 UTC, stefanceriu commented on ElementX/Sources/Services/Media/MediaPlayerProtocol.swift
> +    func pause()
I think it would be easier to understand the API if you keep `play` and `pause` as counterparts and use `load(from mediaSource)` instead

2023-10-02 14:37 UTC, stefanceriu commented on ElementX/Sources/Services/Audio/AudioCacheManager.swift
> +class AudioCacheManager {
This guy doesn't actually manage anything, just exposes a bunch of methods. The AudioPlayer does all the heavy lifting

2023-10-02 14:37 UTC, stefanceriu commented on ElementX/Sources/Services/Audio/AudioPlayer.swift
> +                let audioConverter = AudioConverter()
I'm pretty sure I don't like AudioPlayers doing their own converting, it feels like another layer should stay in between that manages both conversions and caching but also request deduplication and coalescing. The AudioPlayer's responsibilities should only be to load media, play it back and inform the outside about playback state.

2023-10-02 14:37 UTC, stefanceriu commented on ElementX/Sources/Services/Audio/AudioPlayer.swift
> +    private func disableIdleTimer(_ disabled: Bool) {
Again, not something that belongs in an audio player. It has no knowlege of this is actually correct from the greater application's point of view.

2023-10-02 14:37 UTC, stefanceriu commented on ElementX/Sources/Services/Audio/AudioPlayerState.swift
> +        playing = false
Won't these send unwanted updates?

2023-10-02 14:37 UTC, stefanceriu commented on ElementX/Sources/Services/Audio/AudioPlayerState.swift
> +    private func startPublishProgression() {
```suggestion
    private func startPublishProgress() {
```

2023-10-04 08:22 UTC, nimau commented on ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VoiceMessages/VoiceRoomTimelineView.swift
> +        self.playerState = playerState ?? AudioPlayerState(duration: 0)
done.

2023-10-04 08:23 UTC, nimau commented on ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VoiceMessages/VoiceRoomPlaybackView.swift
>              onPlayPause()
👍

2023-10-04 08:24 UTC, nimau commented on ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VoiceMessages/VoiceRoomPlaybackView.swift
>      private let playPauseButtonSize = CGSize(width: 32, height: 32)
wow, it works well with `@ScaledMetric`

2023-10-04 08:25 UTC, nimau commented on ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
>              return .none
Ok done, you're right, it shouldn't be called for something else.

2023-10-04 08:27 UTC, nimau commented on ElementX/Sources/Services/Media/Provider/MediaPlayerProvider.swift
> +    private var audioCacheManager = AudioCacheManager()
Ok, after the rework, the cache is managed by `VoiceMessageMediaManager`

2023-10-04 08:28 UTC, nimau commented on ElementX/Sources/Services/Media/Provider/MediaPlayerProvider.swift
> +import UniformTypeIdentifiers
Yes, but `audio/ogg` mime type is not recognized as an audio one. I've removed the import.

2023-10-04 08:30 UTC, nimau commented on ElementX/Sources/Services/Audio/AudioPlayer.swift
> +                let audioConverter = AudioConverter()
Ok, a new `VoiceMessageMediaManager` class is in charge of loading and converting the audio file.

2023-10-04 08:34 UTC, nimau commented on ElementX/Sources/Services/Audio/AudioPlayer.swift
> +    private func disableIdleTimer(_ disabled: Bool) {
Ok, I moved it to `AudioPlayerState` as this one is used for UI. As it will be needed for the recording feature, I'll moved this to an `IdleTimeManager` in order to handle this at the application level.

2023-10-04 08:34 UTC, nimau commented on ElementX/Sources/Services/Audio/AudioPlayerState.swift
> +        playing = false
I've simplified it by using an internal state instead of multiple flags.

2023-10-04 09:17 UTC, nimau commented on ElementX/Sources/Services/Audio/AudioPlayer.swift
> +    private func disableIdleTimer(_ disabled: Bool) {
Finally, I removed it. Not sure it is needed for playback.

2023-10-04 12:04 UTC, stefanceriu approved these changes
This looks and works great, nicely done! 👏👏👏

2023-10-04 14:12 UTC, nimau commented on ElementX/Sources/Services/VoiceMessage/VoiceMessageCache.swift
> +class VoiceMessageCache {
👍 done.

2023-10-04 14:38 UTC, nimau commented on ElementX/Sources/Services/VoiceMessage/VoiceMessageMediaManager.swift
> +    func loadVoiceMessageFromSource(_ source: MediaSourceProxy, body: String?) async throws -> URL {
Ok, in a later PR I will update to have something similar to what it's done in `MediaLoader`

2023-10-04 15:55 UTC, nimau commented on ElementX/Sources/Services/VoiceMessage/VoiceMessageMediaManager.swift
> +        if !hasSupportedAudioExtension(url) {
I've updated to allow only ogg files to be loaded by the `VoiceMessageMediaManager`

2023-10-04 16:32 UTC, merged