Set a proper user agent
vector-im/element-x-ios pull request #226
Opened 2022-10-06 19:50 UTC by Johennes

This depends on https://github.com/matrix-org/matrix-rust-sdk/pull/1078 so will only be able to move forward once the SDK has been updated to a version that includes this change.

Fixes #225 

### Pull Request Checklist

- [x] I read the [contributing guide](https://github.com/vector-im/element-ios/blob/develop/CONTRIBUTING.md)
- [x] Pull request contains a [changelog file](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#changelog) in ./changelog.d
- [ ] Pull request includes a [sign off](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#sign-off)

**UI changes have been tested with:**
- [ ] iPhone and iPad simulators in portrait and landscape orientations.
- [ ] Dark mode enabled and disabled.
- [ ] Various sizes of dynamic type.
- [ ] Voiceover enabled.

2022-10-27 06:51 UTC, Johennes commented
As the SDK was updated this is now ready for review. I believe the LFS quota errors are unrelated to my changes but please let me know otherwise.

2022-10-27 10:50 UTC, stefanceriu requested changes

2022-10-27 10:50 UTC, stefanceriu commented on ElementX/Sources/Other/Extensions/Bundle.swift
> +    static let app: Bundle = {
This doesn't seem to be used. What was the initial reason for adding it?

2022-10-27 10:50 UTC, stefanceriu commented on ElementX/Sources/Other/Extensions/String.swift
> +            return self
This is potentially unsafe if it silently fails converiting to ascii. It would be safe to return a nullable and let the user handle it.

2022-10-27 10:50 UTC, stefanceriu commented on ElementX/Sources/Other/Extensions/String.swift
> +        guard CFStringTransform(mutableString, nil, "Any-Latin; Latin-ASCII; [:^ASCII:] Remove" as CFString, false) else {
I wonder if we can use something like `folding(options: .diacriticInsensitive, locale: NSLocale.current)`, seems to be passing all the tests..

2022-10-27 10:50 UTC, stefanceriu commented on ElementX/Sources/Other/UserAgentFactory.swift
> +        makeUserAgent()?.asciified()
If `asciified` is only used here perhaps we should make the String extension private to this file.

2022-10-27 10:50 UTC, stefanceriu commented on ElementX/Sources/Other/UserAgentFactory.swift
> +        let clientVersion = ElementInfoPlist.cfBundleShortVersionString
These should probably be passed as constructor dependencies but I can see why they're not with all the Device/UIDevice/UIScreen etc. usages. Doing that would've helped with mocking the factory for the unit tests which are not entirely bulletproof atm

2022-10-27 10:50 UTC, stefanceriu commented on ElementX/Sources/Other/UserAgentFactory.swift
> +final class UserAgentFactory {
I think tehnically this is a builder not a factory as it only produces strings

2022-10-27 15:59 UTC, Johennes commented on ElementX/Sources/Other/UserAgentFactory.swift
> +#if !os(OSX)
Hm, I thought we needed this because DeviceKit itself didn't support macOS: https://github.com/devicekit/DeviceKit/blob/master/Package.swift#L17

2022-10-27 16:03 UTC, Johennes commented on ElementX/Sources/Other/Extensions/Bundle.swift
> +    static let app: Bundle = {
Oh, I think I was using this before I noticed the `ElementInfoPlist` enum and then forgot cleaning it up. 🤦‍♂️

Thanks for catching. Have removed it now.

2022-10-27 16:06 UTC, Johennes commented on ElementX/Sources/Other/Extensions/String.swift
> +            return self
Oh, excellent point! 👍

2022-10-27 16:20 UTC, Johennes commented on ElementX/Sources/Other/Extensions/String.swift
> +        guard CFStringTransform(mutableString, nil, "Any-Latin; Latin-ASCII; [:^ASCII:] Remove" as CFString, false) else {
It's a bit esoteric but this doesn't seem to work for some emojis (e.g. 🏩). I've added another test case for that. It's possible that there's a way to change that but I couldn't find one easily. The string transform code is ported from AlamoFire's Objective-C code.

2022-10-27 16:30 UTC, Johennes commented on ElementX/Sources/Other/Extensions/String.swift
> +            return self
Interestingly `"someascii".canBeConverted(to: .ascii)` is `false` so I had to add another check to see if the string is already in ASCII.

2022-10-27 16:32 UTC, Johennes commented on ElementX/Sources/Other/UserAgentFactory.swift
> +        makeUserAgent()?.asciified()
I think it'd still have to be `internal` due to the unit tests but I can still move it here if that's ok?

2022-10-27 16:37 UTC, Johennes commented on ElementX/Sources/Other/UserAgentFactory.swift
> +final class UserAgentFactory {
Hm, I thought builder was more of a

```
let userAgent = UserAgentBuilder().setName("foo").setVersion("1.0").build()
```

pattern? Or maybe that's only valid in Java? 😅

It felt a little odd to me from the beginning to have this class with a single method but I couldn't think of a better way.

2022-10-27 16:41 UTC, Johennes commented on ElementX/Sources/Other/UserAgentFactory.swift
> +        let clientVersion = ElementInfoPlist.cfBundleShortVersionString
Yeah, that seems tricky especially since the arguments would also change based on the OS. However, if you want to mock the factory itself, maybe we could just extract a protocol containing only `func makeASCIIUserAgent()` and a mock class returning a predefined value?

2022-10-27 16:43 UTC, Johennes commented on ElementX/Sources/Other/UserAgentFactory.swift
> +final class UserAgentFactory {
Have renamed it now.

2022-10-28 08:47 UTC, stefanceriu commented on ElementX/Sources/Other/UserAgentFactory.swift
> +#if !os(OSX)
Okay, let's leave it alone for now 👍

2022-10-28 08:54 UTC, stefanceriu commented on ElementX/Sources/Other/UserAgentFactory.swift
> +        makeUserAgent()?.asciified()
I'm having second thoughts now, probably not worth the trouble

2022-10-28 08:58 UTC, stefanceriu commented on ElementX/Sources/Other/UserAgentFactory.swift
> +final class UserAgentFactory {
The way I think about is based on what it returns, if from a heterogenous collection of types or just always the same type.

2022-10-28 09:03 UTC, stefanceriu commented on ElementX/Sources/Other/Extensions/String.swift
> +        return mutableString.trimmingCharacters(in: .whitespaces)
Should we add a test for this too?

2022-10-28 09:06 UTC, stefanceriu approved these changes
Great stuff 👍

2022-10-28 14:10 UTC, stefanceriu commented on ElementX/Sources/Other/UserAgentFactory.swift
> +        let clientVersion = ElementInfoPlist.cfBundleShortVersionString
I don't think that's worth it to be honest..

2022-10-28 14:11 UTC, merged

2022-10-28 17:13 UTC, Johennes commented on ElementX/Sources/Other/UserAgentFactory.swift
> +final class UserAgentFactory {
Oh, I see. That makes sense. It's all about the definition, I guess. 🙂

2022-10-28 17:15 UTC, Johennes commented on ElementX/Sources/Other/Extensions/String.swift
> +        return mutableString.trimmingCharacters(in: .whitespaces)
It is actually covered in the `testStripsTheHeartbreakHotel` test. Sorry for only being able to reply after you already merged this. Thanks for the review! Looking forward to see my Element X sessions display nicely in device manager. 🙂