Update codecov
vector-im/element-x-ios pull request #356
Opened 2022-12-07 15:10 UTC by paleksandrs

- excluded some folders that shouldn't be added to test coverage 
- added integration tests flag

2022-12-07 15:24 UTC, stefanceriu requested changes
This looks good but I don't think coverage is enabled for the integration tests https://github.com/vector-im/element-x-ios/blob/develop/ElementX/SupportingFiles/target.yml#L31

2022-12-07 15:24 UTC, stefanceriu commented on codecov.yml
> -  - "ElementX/Source/Generated"  # ignore the folder and all its contents
🤦‍♂️

2022-12-08 07:31 UTC, paleksandrs commented
> This looks good but I don't think coverage is enabled for the integration tests https://github.com/vector-im/element-x-ios/blob/develop/ElementX/SupportingFiles/target.yml#L31

Good catch! Thank you 👍

2022-12-08 07:39 UTC, stefanceriu approved these changes

2022-12-08 08:09 UTC, merged