Timeline UI Tests
vector-im/element-x-ios pull request #380
Opened 2022-12-19 16:14 UTC by pixlwave

This PR adds the main remaining tests for #352.

It also introduces `UITestSignalServer`/`Client` as a way of communicating across processes using UDP. In the future these could be changes to `TCP` and expanded upon, but for now there's a simple enough implementation to send and await a single signal at a time.

2022-12-20 10:39 UTC, stefanceriu requested changes
This looks and works great, nicely done! Left some comments inline

2022-12-20 10:39 UTC, stefanceriu commented on UITests/Sources/RoomScreenUITests.swift
> +        try await signal.connect()
Feels weird to have `signal` `connect` to anything. We should probably use a different name e.g. plainly `server`

2022-12-20 10:39 UTC, stefanceriu commented on ElementX/Sources/UITests/UITestSignalling.swift
> +class UITestSignalServer: UITestSignalProtocol {
We should probably call this `UITests` to match the other classes.
I was also under the impression that we'll go with classes nested withing it i.e. `UITestsSignalling.Server` and `UITestsSignalling.Client`

2022-12-20 10:39 UTC, stefanceriu commented on ElementX/Sources/UITests/UITestSignalling.swift
> +    let listener: NWListener
This one can be private

2022-12-20 10:39 UTC, stefanceriu commented on ElementX/Sources/UITests/UITestSignalling.swift
> +protocol UITestSignalProtocol: AnyObject {
```suggestion
protocol UITestsSignallingProtocol: AnyObject {
```

2022-12-20 10:39 UTC, stefanceriu commented on UITests/Sources/RoomScreenUITests.swift
> +        signal.disconnect()
Would probably be cleaner to use a `defer` for these

2022-12-20 10:39 UTC, stefanceriu commented on ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
> +    private let signal = UITestSignalClient()
Do we really want to create this from the get go?

2022-12-20 10:39 UTC, stefanceriu commented on ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
> +    private func enableServerSimulation() async throws {
Not sure "server simulation" is the best name for what we're doing here

2022-12-20 10:39 UTC, stefanceriu commented on ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
> +            // Keep listening TODO: Try an async stream here?
Yes please! And if that doesn't work move this whole thing to a normal loop

2022-12-23 08:46 UTC, stefanceriu commented
Note, I've manually disabled CI UI tests until this PR is merged as they keep failing every night

2023-01-05 11:15 UTC, pixlwave commented on ElementX/Sources/UITests/UITestSignalling.swift
> +class UITestSignalServer: UITestSignalProtocol {
Oh yeah, I looked at `UITestScreenIdentifier` and didn't notice the others are plural. Makes sense 👍

2023-01-05 11:36 UTC, pixlwave commented on ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
> +    private let signal = UITestSignalClient()
Probably not 🙃

2023-01-05 12:30 UTC, pixlwave commented on ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
> +            // Keep listening TODO: Try an async stream here?
I went with the normal loop in the end.

2023-01-05 15:25 UTC, pixlwave commented on ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemBubbledStylerView.swift
> +                .padding(timelineItem.isOutgoing ? .leading : .trailing, 40) // Extra padding to differentiate alignment.
I don't think this change should have happened - it more closely matches Figma this way.

2023-01-05 15:27 UTC, pixlwave commented on UITests/Sources/Application.swift
> +    func assertScreenshot(_ identifier: UITestScreenIdentifier, step: Int? = nil, insets: UIEdgeInsets? = nil) {
I've added the option to crop the snapshot to ignore for example the navigation bar which may change in opacity depending on whether a scrollview is at the top or has content under the bar.

2023-01-05 16:35 UTC, merged