Added a progress tracker to the bug report view
vector-im/element-x-ios pull request #513
Opened 2023-02-01 15:55 UTC by Velin92

Added a custom progress tracker class that can be used to observe progress in a data task.
Such object can be attached to a user notification and user to observe the progress of any loading to create progress views that track such progress.

Other improvements I want to add:

- [ ] The signature for `submitBugReport` is too big, maybe is worth create a dedicated struct
- [ ]  Move the ProgressTracker class in a specific file
- [ ] I guess I could add a mock version of the UserNotificationView that also displays a progress bar

2023-02-07 11:15 UTC, stefanceriu requested changes
Left a couple of comments inline, hope they make sense.

Also, unrelated to your PR (I noticed in the video) but I think the transition animation for the modal is wrong. It should probably be a simple `.opacity` instead of the `asymmetric .top .bottom` it's doing now. Would appreciate it if you could have a look at it.

2023-02-07 11:15 UTC, stefanceriu commented on ElementX/Sources/Screens/BugReport/BugReportViewModel.swift
> +                                                                    progressTracker: progressTracker)
Should the BugReportService be the one that provides the progress through a simple value combine publisher? The fact that the `ProgressTracker` is now a `URLSessionTaskDelegate` leaks internal details for no good reason.
The `ProgressTracker` should probably be a simple protocol and have different services provide progress in whatever way they choose fit.

2023-02-07 11:15 UTC, stefanceriu commented on ElementX/Sources/Other/ProgressTracker.swift
> +    func urlSession(_ session: URLSession, didCreateTask task: URLSessionTask) {
See my comment below but I don't think this belongs here. The fact that the BugService is using an URLSession should remain an implementation detail.

2023-02-07 11:15 UTC, stefanceriu commented on ElementX/Sources/Other/ProgressTracker.swift
> +            .receive(on: RunLoop.main)
Why is this RunLoop.main instead of DispatchQueue.main?

2023-02-07 11:15 UTC, stefanceriu commented on ElementX/Sources/Other/ProgressTracker.swift
> +    var progressFractionPublisher: AnyPublisher<Double, Never> {
Let's simply name this `progressPublisher`

2023-02-07 11:15 UTC, stefanceriu commented on ElementX/Sources/Other/ProgressTracker.swift
> +    @Published private var progressFraction: Double
Why do we even need to store this if we're just passing values through?  Might be a good idea to expose a CurrentValueSubject instead

2023-02-07 11:15 UTC, stefanceriu commented on ElementX/Sources/Other/UserNotifications/UserNotificationModalView.swift
> +                    ProgressView(value: progressFraction)
We might want to set a max frame width now that this has been introduced

2023-02-07 12:12 UTC, stefanceriu commented on ElementX/Sources/Other/ProgressTracker.swift
> +    @Published private var progressFraction: Double
Also, does this `@Published` even work without it being an `ObservableObject`?

2023-02-07 17:25 UTC, Velin92 commented on ElementX/Sources/Other/ProgressTracker.swift
> +    @Published private var progressFraction: Double
Yup, @Published is just essentially creating a wrapped publisher of type `CurentValueSubject<T,Never>` where `T` is the type of the variable, if the variable is also contained in an `ObservavbleObject`, it will fire the `objectWillChange.send()` otherwise the `objectWillChange.send()`  will not be called.

However you can still listen to the changes of the wrapped publisher. I usually just find more readable, easier and faster to write a simple a `Published var` instead of a `CurentValueSubject` if I know that there is no error case, and that if the `Failure`  type is `Never`

2023-02-07 17:28 UTC, Velin92 commented on ElementX/Sources/Other/ProgressTracker.swift
> +    @Published private var progressFraction: Double
`CurrentValueSubject` would still store a value, since it has an `init` with value and a `value` field, also explained the reason for my preference in the other comment. However since they are essentially almost the same thing I can use a `CurrentValueSubject` instead.

2023-02-07 17:30 UTC, Velin92 commented on ElementX/Sources/Other/ProgressTracker.swift
> +            .receive(on: RunLoop.main)
Uhm `DispatchQueue.main` is actually better now that I think of it... `RunLoop.main` can get busy by user interactions making it less for general use.

2023-02-07 17:35 UTC, Velin92 commented
> Left a couple of comments inline, hope they make sense.
> 
> Also, unrelated to your PR (I noticed in the video) but I think the transition animation for the modal is wrong. It should probably be a simple `.opacity` instead of the `asymmetric .top .bottom` it's doing now. Would appreciate it if you could have a look at it.

Will give a look at the presentation issue.
I see is actually also happening on TF, so maybe is some kind of regression, so you want me to take a look at it in a different PR/branch tomorrow (I'll be back from my holidays/leave), unrelated to the progress tracker?

2023-02-08 08:51 UTC, stefanceriu commented on ElementX/Sources/Other/ProgressTracker.swift
> +    @Published private var progressFraction: Double
That's pretty smart, didn't tink about it like that before.

I'm generaly weary of using SwiftUI specific wrappers in other places and in this particular case it seems there's a few gotchas with it: it fires on `willChange` instead of `didChange` and is restricted to structs https://www.avanderlee.com/swiftui/published-property-wrapper/

As for protocols, presumably you would stilexpose a `CurentValueSubject` if you need access to the current value without exposing a separate property, no?

2023-02-08 08:52 UTC, stefanceriu commented
> Will give a look at the presentation issue.
> I see is actually also happening on TF, so maybe is some kind of regression, so you want me to take a look at it in a different PR/branch tomorrow (I'll be back from my holidays/leave), unrelated to the progress tracker?

I don't think it's a regression, I think I just copy pasted it from the `UserNotificationToastView` and forgot to change the animation style. Up to you if you want to handle it in this PR or separately. The change should be pretty simple:
`.transition(.opacity)` instead of that custom `toastTransition: AnyTransition`

2023-02-08 09:15 UTC, Velin92 commented on ElementX/Sources/Other/ProgressTracker.swift
> +    @Published private var progressFraction: Double
The thing is that the `@Published` technically speaking is part of Combine (even if you don't even need to import it, to use it, Foundation is sufficient), but yeah it is constricted to structs.

For protocols yeah if you really need to use one you could either do that with a `CurrentValueSubject` which could use the `$` publisher of the struct since it's literally a `CurrentValueSubject` (if you use `po` you will see it), or you can have the protocol expose the value directly as T, and have an AnyPublisher<T, Never>, and in the implementation use the `@Published`, depends if you really want to have the interface clearly say that the value will be published or you want to hide it.

Regarding the willSet, that could be risky if you have a case where you are listening to the change provided by the publisher... but at the same time you also checking for the value wrapped in the publisher... which would not really make a lot of sense to use it in that way.

2023-02-08 17:46 UTC, stefanceriu approved these changes
Looking good, nicely done! 👏

2023-02-08 20:52 UTC, merged