Attach Screenshot in Bug Report Screen
vector-im/element-x-ios pull request #578
Opened 2023-02-14 17:43 UTC by Velin92

Added an Attach Screenshot button that will add a screenshot to the bug report:

https://user-images.githubusercontent.com/34335419/218816083-fe65326e-db36-4b34-a542-efd89d4afe91.MP4

2023-02-14 18:52 UTC, pixlwave approved these changes
Looks good to me. One small comment from the screen recording, could the progress bar say "Sending" instead of loading?

Also should probably ask for a design review on this :)

2023-02-14 18:52 UTC, pixlwave commented on ElementX/Sources/Screens/BugReport/BugReportViewModel.swift
> +                let imageURL = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("Screenshot.png")
Small nicety:
```suggestion
                let imageURL = URL.temporaryDirectory.appendingPathComponent("Screenshot.png")
```

2023-02-14 18:52 UTC, pixlwave commented on ElementX/Sources/Screens/BugReport/View/BugReportScreen.swift
> +            ) {
Sorry, style:
```suggestion
            PhotosPicker(selection: $selectedScreenshot,
                         matching: .screenshots,
                         photoLibrary: .shared()) {
```

2023-02-14 19:04 UTC, pixlwave commented on ElementX/Sources/Screens/BugReport/View/BugReportScreen.swift
> +            ) {
I've created https://github.com/vector-im/element-x-ios/pull/579

2023-02-15 08:10 UTC, stefanceriu approved these changes
lgtm too 👍

2023-02-15 12:12 UTC, amshakal requested changes
Hey!! Thanks for working on this. I have a few suggestions/tweaks:
1. Is it possible be reduce the size of the text box so that the info/buttons below it are more visible?
2. Can we add the 'attach screenshot' button above 'send logs'? It fit's better with the overall heiarchy of this screen.
3.  Can we add an icon to the left of attach screenshot to make it super obvious what the user is supposed to do here, it also matches with the treatment we are giving buttons within settings. 

Screenshot for ref:
<img width="563" alt="Screenshot 2023-02-15 at 12 11 30 pm" src="https://user-images.githubusercontent.com/85162587/219024034-1c6e32f9-ca74-44b1-a32e-72f5abcd4422.png">

Figma file for ref:
https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=123%3A21855&t=cBA1DmfD4awGuMCW-1

2023-02-15 14:33 UTC, pixlwave approved these changes
Changes look good to me. There's a couple more places where we could use the label style: `RoomDetailsScreen` in the `aboutSection` and the `securitySection`.

2023-02-15 14:33 UTC, pixlwave commented on ElementX/Sources/Other/SwiftUI/Views/SettingsDefaultRow.swift
> +                                          backgroundColor: .element.systemGray6))
Seems these 2 colours were wrong. They should be `secondaryContent` and `formBackground` just like you did in the bug report screen. Can we update this and hard code them into the style?

2023-02-15 14:33 UTC, pixlwave commented on ElementX/Sources/Other/SwiftUI/Views/RowLabelStyle.swift
> +struct RowLabelStyle: LabelStyle {
Should probably call this `SettingsRowLabelStyle` to match the others. I think at some point it might make sense to rename all of the `Settings...` items to `Form...` to be less specific.

2023-02-15 15:09 UTC, amshakal approved these changes
💯

2023-02-15 15:12 UTC, pixlwave commented on ElementX/Sources/Other/SwiftUI/Views/SettingsRowLabelStyle.swift
> +    }
You could just go for
```
var alignment: VerticalAlignment = .center
```
and use the synthesised init here.

Personally I'd be tempted to use `.firstTextBaseline` as the default too.

2023-02-15 16:46 UTC, merged