Fixed UI test problems introduced after the accessibility identifier …
vector-im/element-x-ios pull request #586
Opened 2023-02-15 15:51 UTC by stefanceriu

…changes

2023-02-15 16:28 UTC, Velin92 requested changes
Maybe would be better to remove the line `"parallelizable" : true` from the UI tests .xctestplan to avoid multiple UI tests to run in parallel, which seems to break the testing in Xcode. (At least for me locally).

Also the following screenshot test seems to be failing:
```
class OnboardingUITests: XCTestCase {
    func testInitialStateComponents() {
        let app = Application.launch(.onboarding)
        app.assertScreenshot(.onboarding)
    }
```

2023-02-16 06:53 UTC, stefanceriu commented
> Maybe would be better to remove the line `"parallelizable" : true` from the UI tests .xctestplan to avoid multiple UI tests to run in parallel, which seems to break the testing in Xcode. (At least for me locally).

I think we should, doesn't work properly for me either

2023-02-16 07:08 UTC, stefanceriu commented
> Also the following screenshot test seems to be failing:

Seems we have broken our `elementFallbackLanguage` in the UITests refactoring

![Screenshot 2023-02-16 at 08 56 47](https://user-images.githubusercontent.com/637564/219292865-a0360d43-4db4-4e8d-95f8-21a87f2e4d78.png)

2023-02-16 10:19 UTC, pixlwave approved these changes
LGTM

2023-02-16 10:19 UTC, pixlwave commented on ElementX/Sources/UITests/UITestsAppCoordinator.swift
> +        Bundle.elementFallbackLanguage = "en"
Whoops sorry, didn't think about that!

2023-02-16 10:19 UTC, pixlwave commented on UITests/Sources/Application.swift
> -        Bundle.elementFallbackLanguage = "en"
I think this is about setting the fallback language in the tests runner? Not sure it really matters with our strings though.

2023-02-16 10:32 UTC, pixlwave commented on UITests/Sources/Application.swift
> -        Bundle.elementFallbackLanguage = "en"
Changed my mind, we probably do need to keep this to match a label value in the tests to what is shown in the app when running in German.

2023-02-16 10:38 UTC, pixlwave approved these changes

2023-02-16 10:42 UTC, merged