Add the DesignKit package to the project.
vector-im/element-x-ios pull request #64
Opened 2022-05-27 17:11 UTC by pixlwave

Following on from #57, this PR adds the package to the project and uses it in the login screen.

2022-05-27 17:15 UTC, pixlwave commented on DesignKit/Sources/TextFields/BorderedInputFieldStyle.swift
> +            .padding(.vertical, 12.0)
I need to double check this is accurate, but it looks nicer when enabling dynamic type.

2022-05-27 17:16 UTC, pixlwave commented on DesignKit/Sources/TextFields/BorderedInputFieldStyle.swift
> +                }
We can use `.submitLabel` on iOS 15 now.

**Note:** Thinking about this, it will affect text fields in EI when using the package 😕

2022-05-27 17:22 UTC, pixlwave commented on ElementX/Sources/Screens/LoginScreen/View/LoginScreen.swift
> +                .buttonStyle(.primaryAction())
Looking at the Figma, I think this is an "Extra Large CTA" so this should be `.elementActionXL`. And the secondary action seems to be `.elementGhostXL`.

2022-06-01 18:09 UTC, pixlwave commented on DesignKit/Sources/Buttons/SecondaryActionButtonStyle.swift
> +        return isPressed ? 0.6 : 1.0
https://github.com/vector-im/element-ios/pull/6204#discussion_r884537843

2022-06-08 17:48 UTC, pixlwave commented on ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "7.16.0"
Seeing this, I think Xcode might be trying to be "helpful" whenever it resolves packages: makes me wonder if the DesignTokens repo needs tagging (or specifying by commit rather than branch) otherwise navigating back in history could be hard.

2022-06-08 17:52 UTC, pixlwave commented on ElementX/Sources/Screens/LoginScreen/View/LoginScreen.swift
> +                .buttonStyle(.elementAction(.xLarge))
The other option here would be `.elementAction.xLarge`, I could give that a go if that sounds any better.

However with a custom colour it would be `.elementAction(color: .pink).xLarge` which probably doesn't read quite as well as `.elementAction(.xLarge, color: .pink)`.

2022-06-08 22:32 UTC, ismailgulek requested changes
Looks great. Just a couple of comments.

2022-06-09 11:58 UTC, pixlwave commented on DesignKit/Sources/Buttons/ElementActionButtonStyle.swift
> +    public init(size: ElementControlSize = .xLarge, color: Color = .element.accent) {
Ah yeah good point. I was trying to keep this source compatible with EI but then I decided it was better to rename it so that makes way more sense 👍

2022-06-09 12:01 UTC, pixlwave commented on ElementX/Sources/Screens/LoginScreen/View/LoginScreen.swift
> +                .focused($focussedField, equals: .username)
TBH, its probable a bit overkill to have the `.focused` modifier on it, but what happens is when the text field becomes focused, it updates `focussedField` to `.username` automatically. It means we could query which component has focus and change logic based on that at some point.

2022-06-09 12:26 UTC, pixlwave commented on DesignKit/Sources/TextFields/ElementTextFieldStyle.swift
> +}
Good shout, also made me realise that `isError` should be the last parameter and that the stack wasn't actually aligned properly. Annoyingly previews from a package currently crash Xcode, but its a known bug. I might move the previews into the EX project in a future PR 🤔

2022-06-09 12:48 UTC, pixlwave commented on DesignKit/Sources/Buttons/SecondaryActionButtonStyle.swift
> +        return isPressed ? 0.6 : 1.0
I'm going to leave this for now. Both of the `0.6` values would have to be defined, and it is pretty clear from the code that the first is the disabled opacity and the second is the pressed opacity. Hopefully values like these will come from the DesignTokens package at some point anyway, and then they can be shared between all button styles etc.

2022-06-09 13:14 UTC, ismailgulek commented on ElementX/Sources/Screens/LoginScreen/View/LoginScreen.swift
> +                .focused($focussedField, equals: .username)
Ah i didn't get it from the code 🤦‍♂️, ignore me.

2022-06-09 13:44 UTC, merged