Hide the avatar when the Dynamic Text is large
vector-im/element-x-ios pull request #690
Opened 2023-03-08 12:50 UTC by sempruijs

Currently, when the user has larger font on (settings > accessibility > display & text size  > larger text) and they try to read the content in the Home Screen, the profile pictures are so big that they cannot read the groep name anymore.

I think the group name and the preview message is more important than someones profile picture. (And  whatsapp agrees with me)

![old, a screenshot of the home view where the profile pictures are too big](https://user-images.githubusercontent.com/19208988/223716895-28c19a54-afd6-4c61-ad5d-e1aaa1ccbd0d.png)

This pr fixes that by hiding the avatar when the user has a larger text size.

![normal, a screenshot with the regular text size](https://user-images.githubusercontent.com/19208988/223716893-4a120ea3-cfab-4d1f-9a2b-56d0dba2119c.png)
![fixed, a screenshot of the home view with larger text, where the profile pictures are hidden ](https://user-images.githubusercontent.com/19208988/223716887-d7534539-7c61-437a-8e10-5ca3ad109d52.png)

### Pull Request Checklist

- [x] I read the [contributing guide](https://github.com/vector-im/element-ios/blob/develop/CONTRIBUTING.md)
- [x] Pull request contains a [changelog file](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#changelog) in ./changelog.d
- [x] Pull request includes a [sign off](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#sign-off)

**UI changes have been tested with:**
- [x] iPhone and iPad simulators in portrait and landscape orientations.
- [x] Dark mode enabled and disabled.
- [x] Various sizes of dynamic type.
- [x] Voiceover enabled.

2023-03-08 12:53 UTC, sempruijs commented
Signed-off-by: Sem Pruijs <sem@pruijs.net>

2023-03-08 13:09 UTC, cor commented
LGTM

2023-03-08 15:36 UTC, pannie commented
LGTM

2023-03-09 17:02 UTC, pixlwave requested changes
Hey @sempruijs thanks for this PR. I've run it past our design team and there are a couple of tweaks we would like to make:
- Hide the avatar at AX3.
- Don't allow the avatar to grow any bigger than AX1.

I've included suggestions in your PR for this :)

We've realised we will need to create designs for a different cell layout when using the larger AX sizes at some stage in the future to hopefully improve things further for visually impaired users.

2023-03-10 09:17 UTC, sempruijs commented
Ahhh thanks for the suggestions! I can implement them probably somewhere next week :) 

I am very happy that you take accessibility serious. My goal is to make element x the most accessible private messenger and I am glad that you give feedback and help me along the way to make the app and me as a developer better ❤️

2023-03-10 09:30 UTC, pixlwave commented on ElementX/Sources/Screens/HomeScreen/View/HomeScreenRoomCell.swift
> +    @Environment(\.dynamicTypeSize) var size
One last suggestion looking through this again. Its nice to keep the name of environment values consistent with their keys:
```suggestion
    @Environment(\.dynamicTypeSize) private var dynamicTypeSize
```

2023-03-20 09:58 UTC, merged