Leave Room
vector-im/element-x-ios pull request #699
Opened 2023-03-14 01:14 UTC by Velin92

Implementing the leave room ui and functionality

2023-03-16 09:34 UTC, Velin92 commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsViewModel.swift
> +            // TODO: What do we want to show here in case of error?
@pixlwave something like... "Failed to leave the room, please try again later"?

2023-03-16 10:22 UTC, callumu commented
This looks great, thanks!

2023-03-16 12:39 UTC, Velin92 commented on UnitTests/Sources/NavigationSplitCoordinatorTests.swift
> +                XCTAssertTrue(self.navigationSplitCoordinator.compactLayoutStackModules.isEmpty)
@pixlwave  this was the issue, since now we are popping to root this should be empty right?

2023-03-16 15:31 UTC, pixlwave requested changes
Niiice addition 👏 Sorry though, I added quite a few comments.

2023-03-16 16:30 UTC, callumu commented
Actually one thing I noticed - The 'R' of room shouldn't be capitalised

2023-03-16 17:24 UTC, callumu commented
@Velin92 

> for the Leave Room copy I am actually using an existing already translated copy that we already have coming from the existing application, maybe we can just remove the capital R from the existing copy in the future

Sure, so in the future updating the copy in one place will update it everywhere?

2023-03-16 17:35 UTC, Velin92 commented on UnitTests/Sources/NavigationSplitCoordinatorTests.swift
> +                expectation.fulfill()
wouldn't the` self.navigationSplitCoordinator.compactLayoutStackCoordinators` be an empty array? since in my specific case we are having the navigation modules empty too?

2023-03-17 11:21 UTC, pixlwave commented on ElementX/Sources/Screens/RoomDetails/View/RoomDetailsScreen.swift
> +        })
There's a SwiftLint rule for it, but it last time I tried it, it didn't cover initialisers annoyingly. Maybe we should enable it anyway.

2023-03-17 11:23 UTC, pixlwave commented on UnitTests/Sources/NavigationSplitCoordinatorTests.swift
> +                expectation.fulfill()
Oh yes that's the right thing here, lets add that assertion :)

2023-03-17 11:26 UTC, Velin92 commented on UnitTests/Sources/NavigationSplitCoordinatorTests.swift
> +                expectation.fulfill()
done!

2023-03-17 11:36 UTC, pixlwave approved these changes
LGTM 🚪

2023-03-17 11:36 UTC, pixlwave commented on ElementX/Sources/Mocks/RoomProxyMock.swift
> +    convenience init(with configuration: RoomProxyMockConfiguration) {
Can we get rid of the `configuration` and put the parameters directly in here?

2023-03-17 11:36 UTC, pixlwave commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsCoordinator.swift
>                  self.callback?(.leaveRoom)
This one should be `leftRoom` too right? And recursively if that one maps to a `leaveRoom` then keep on updating them all the way up to the flow coordinator.

2023-03-17 11:36 UTC, pixlwave commented on ElementX/Sources/Services/UserSession/UserSessionFlowCoordinator.swift
>                  case .leaveRoom:
```suggestion
                case .leftRoom:
```

2023-03-17 11:36 UTC, pixlwave commented on ElementX/Sources/Services/UserSession/UserSessionFlowCoordinator.swift
> +    private func leaveRoom() {
Maybe this should be called `popRoom`/`deselectRoom`/`dismissRoom` or similar.

2023-03-17 11:36 UTC, pixlwave commented on ElementX/Sources/Screens/RoomDetails/View/RoomDetailsScreen.swift
> +                    .labelStyle(FormRowLabelStyle(titleColor: .element.alert,
Nice, thanks 🙏

2023-03-17 13:24 UTC, pixlwave approved these changes
Makes sense, 1 nice little tweak you could do.

2023-03-17 13:24 UTC, pixlwave commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsViewModel.swift
> +            state.bindings.leaveRoomAlertItem = LeaveRoomAlertItem(subtitle: roomProxy.isPublic ? ElementL10n.roomDetailsLeaveRoomAlertSubtitle : ElementL10n.roomDetailsLeavePrivateRoomAlertSubtitle)
Would probably be neater to put these string calculations inside `LeaveRoomAlertItem` and initialise it with an enum of `public`, `private`, `empty` so that when we add say a content menu on the room we don't duplicate the string logic.

2023-03-17 13:57 UTC, merged

2023-03-17 14:44 UTC, pixlwave commented on ElementX/Sources/Mocks/RoomProxyMock.swift
> +    convenience init(with configuration: RoomProxyMockConfiguration) {
Ah interesting, so that solves my thought for presets 👍