Rageshake Service
vector-im/element-x-ios pull request #70
Opened 2022-05-31 19:51 UTC by ismailgulek

Fixes #23
Fixes #24 
Fixes #61

2022-06-02 10:38 UTC, ismailgulek commented on ElementX/Sources/Screens/BugReport/View/BugReport.swift
> +            return AnyView(
Great, thanks.

2022-06-02 11:18 UTC, ismailgulek commented on ElementX/Sources/Services/BugReport/BugReportService.swift
> +         applicationId: String = "riot-ios",
It should match with server configuration.

2022-06-02 11:43 UTC, ismailgulek commented on ElementX/Sources/Screens/Settings/View/Settings.swift
> +        VStack {
thanks for the suggestion, looks much better :)

2022-06-02 12:00 UTC, ismailgulek commented on UnitTests/Sources/ScreenshotDetectorTests.swift
> +            detector.callback = { _, _ in
I've tried different versions of this before, need to play more with these actors :/

2022-06-02 12:26 UTC, ismailgulek commented on ElementX/Resources/Assets.xcassets/Images/sample_screenshot.imageset/Contents.json
> +{
Investigated this a bit, didn't seem very possible. I've fixed this by adding sample screenshot to test target directly and removing from the app target.

2022-06-02 12:42 UTC, ismailgulek commented on ElementX/Sources/Services/BugReport/ScreenshotDetector.swift
> +class ScreenshotDetector {
Yes, i'm aware of that. I'm planning to improve this later, by disabling `autoRequestPHAuthorization` and then implementing file attachment functionality in the bug report screen.

If it's too disturbing i can disable `autoRequestPHAuthorization` now and make this functionality best-effort.

2022-06-03 10:56 UTC, stefanceriu requested changes
Great stuff 👏  Just a few comments inline.

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/AppCoordinatorStateMachine.swift
> +                    return .homeScreen
This transition shouldn't be necessary as you're already handling the same one above in `machine.addRoutes(event: .dismissedSettingsScreen, transitions: [ .settingsScreen => .homeScreen ])`

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/BuildSettings.swift
> +final class BuildSettings {
👍

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/Services/BugReport/BugReportService.swift
> +    var applicationId: String
Shall we move this to the top and make it private (i.e. remove it from the protocol)?

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/Services/BugReport/BugReportService.swift
> +    var applicationWasCrashed: Bool {
Can I suggest maybe replacing this with `hasApplicationPreviouslyCrashed` or even sentry's own `crashedLastRun`?

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/AppCoordinator.swift
> +            fatalError("")
You could remove the quotes here entirely or maybe add a comment à la "Invalid bug report service base URL". Another option would be to move this into a throwing constructor and check the `bugReportSentryEndpoint`for empty too.

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/AppCoordinator.swift
> +        screenshotDetector.callback = askAfterScreenshot
If I might suggest `processScreenshotDetection` instead of `askAfterScreenshot`.

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/Services/BugReport/ScreenshotDetector.swift
> +    @objc @MainActor private func userDidTakeScreenshot() {
I think we can make the whole class a @MainActor 🤔

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/Services/BugReport/ScreenshotDetector.swift
> +class ScreenshotDetector {
I would say let's leave it in for now. It's easy enough to remove or change later.

Otherwsie, Isn't there also a flow in which the user takes the screenshot but doesn't end up saving it to the photo library? I take a lot of screenshots that I just copy to the pasteboard and delete afterwards.
I think the only good option is to let the user choose when/if they want to attach a screenshot.

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/Services/BugReport/BugReportService.swift
> +                return nil
Don't we need to return back the `event` from here instead of `nil`?

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/Generated/InfoPlist.swift
> +internal enum ElementInfoPlist {
Nice! 👍

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/Other/UIImage+Element.swift
> +    func anonymized(confidenceLevel: Float = 0.5, fillColor: UIColor = .red) async throws -> UIImage {
😍 
I wouldn't have made it a public extension though as it feels very specific to the bug report flows. Maybe a static method on a ImageAnonymizer struct is enough.

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/Screens/BugReport/View/BugReport.swift
> +            Button { context.send(viewAction: .cancel) } label: {
These buttons when stacked together cover quite a bit part of the screen. I would remove the `cancel` one as you can always navigate backwards and implicitly cancel.

2022-06-03 10:56 UTC, stefanceriu commented on ElementX/Sources/Screens/HomeScreen/HomeScreenCoordinator.swift
> +                self.callback?(.settings)
`Settings` is a bit generic, maybe `presentSettings` instead. Could do the same for rooms `presentRoom(roomIdentifier: String)? 🤔

2022-06-03 10:56 UTC, stefanceriu commented on UnitTests/Sources/ScreenshotDetectorTests.swift
> +            NotificationCenter.default.post(name: UIApplication.userDidTakeScreenshotNotification, object: nil)
I think this will invoke the system permissions dialog on the CI which might break the UI tests.

2022-06-03 10:56 UTC, stefanceriu commented on UnitTests/Sources/ImageExtensionTests.swift
> +class ImageExtensionTests: XCTestCase {
You'll need to add `- path: ../Resources` to the UnitTests xcodegen target.yml but the tests would still fail. There's an exception being thrown from the anonymized VNImageRequestHandler -> `Error Domain=com.apple.vis Code=9 "encountered an unexpected condition: Unspecified error" UserInfo={NSLocalizedDescription=encountered an unexpected condition: Unspecified error}`

2022-06-03 11:00 UTC, stefanceriu commented
> Should we be adding `MXLogger` in its current form as an objc class

I also agree that we should try to get rid of it but at the moment, apart from crash reporting, it's also handling the logging to files and log rotations. Let's tackle this separately when we investigate Logger and rust side logs.

2022-06-03 11:47 UTC, ismailgulek commented on ElementX/Sources/AppCoordinatorStateMachine.swift
> +                    return .homeScreen
Hmm, forgot this one yeah. First i thought this was needed.

2022-06-03 11:52 UTC, ismailgulek commented on ElementX/Sources/AppCoordinator.swift
> +            fatalError("")
Yeah forgot to fill the fatal error, but a throwing constructor made more sense :)

2022-06-03 13:39 UTC, ismailgulek commented on UnitTests/Sources/ScreenshotDetectorTests.swift
> +            NotificationCenter.default.post(name: UIApplication.userDidTakeScreenshotNotification, object: nil)
Right, i've updated `autoRequestPHAuthorization` for tests and checked the current authorization status on the device.

2022-06-03 14:06 UTC, ismailgulek commented on UnitTests/Sources/ImageExtensionTests.swift
> +class ImageExtensionTests: XCTestCase {
I think updating the yaml file fixed it!

2022-06-03 14:08 UTC, ismailgulek commented on ElementX/Sources/Services/BugReport/ScreenshotDetector.swift
> +class ScreenshotDetector {
I think it saves the screenshot first and remove if you want afterwards. As we show the popup as soon as the screenshot taken, it seems fine to me. I agree the real solution would be adding functionality to add files into the bug report screen, which i'm planning to provide later.

2022-06-03 14:20 UTC, ismailgulek commented on ElementX/Sources/Screens/BugReport/View/BugReport.swift
> +            Button { context.send(viewAction: .cancel) } label: {
Good idea, i've added a cancel bar button item when we present this screen.

2022-06-03 14:24 UTC, stefanceriu approved these changes
👏 👏

2022-06-06 06:15 UTC, toshanmugaraj commented on ElementX/Sources/Services/BugReport/ScreenshotDetector.swift
> +class ScreenshotDetector {
I would prefer the screenshot option is disabled by default. 
In many cases, it shares the sensitive information to the Rageshake service, and not much helpful. 
I see in one of the demo in Matrix web client, they blur the all dynamic contents while taking the screenshot for Rageshake.

2022-06-06 08:47 UTC, pixlwave commented on ElementX/Sources/Services/BugReport/ScreenshotDetector.swift
> +class ScreenshotDetector {
> If it's too disturbing i can disable autoRequestPHAuthorization now

No no, like Stefan said, its fine for now :)

2022-06-06 08:47 UTC, pixlwave commented on ElementX/Resources/Assets.xcassets/Images/sample_screenshot.imageset/Contents.json
> +{
That sounds even better TBH 👍

2022-06-06 08:48 UTC, pixlwave commented
> I also agree that we should try to get rid of it but at the moment, apart from crash reporting, it's also handling the logging to files and log rotations. Let's tackle this separately when we investigate Logger and rust side logs.

Ah yeah that makes more sense :)

2022-06-06 09:38 UTC, merged