Show or create direct message room
vector-im/element-x-ios pull request #716
Opened 2023-03-21 16:45 UTC by flescio

Resolve: https://github.com/vector-im/element-x-ios/issues/595

New flow for creating a direct room or presenting an already existing one.

![dm_rooms](https://user-images.githubusercontent.com/20090282/226681339-847fff27-afad-465c-8641-1964e4e8be88.gif)

2023-03-22 10:58 UTC, stefanceriu requested changes

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatCoordinator.swift
>                  // TODO: start create room flow
Please refrain from adding todo's unless it's something that you're actually blocked on.

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatCoordinator.swift
>                  // TODO: start create room flow
Same here

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatCoordinator.swift
> +            case .userSelected(let user):
`close` and `createRoom` are imperatives so this one should be too: `selectUser` to keep them consistent. Also worth mentioning that we select an `User` but the associated value is a `Member`. We should probably just stick with one of them

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatCoordinator.swift
> +            case .userSelected(let user):
On another note, why don't we handle this logic in the viewModel directly instead of forwarding it up to the coordinator?

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatModels.swift
> +    // user resulting from search
Remove this comment, doesn't help in any way

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatModels.swift
>      // TODO: bind with real service, and mock data only in preview
Same here

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatModels.swift
> +    case userSelected(RoomMemberProxy)
Same comment as above `selectUser`

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatModels.swift
> +    var searchedUsers: [RoomMemberProxy] = []
Let's maybe rename this to something more appropiate like `searchResults` or `suggestedUsers`

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatViewModel.swift
> +        start()
What's this about, why do need a start method? If you really want to extract that code call is something appropiate e.g. `setupBindings`

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatViewModel.swift
> +        case .failedCreatingRoom: // this will likely be in the Room's screen while sending the first message
Same ask with this comment as well. Don't leave comments for things that aren't 100% clear. `Will likely` doesn't bring any value in the long run

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatViewModel.swift
>              // TODO: start invite people flow
Same as the others

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/View/StartChatScreen.swift
> +                searchedUsersSection
This links to the comment above, let's go with `userSuggestionSection` or whatever

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/View/StartChatScreen.swift
> +                    .onTapGesture {
Shouldn't this be a Button instead so it gets correct highlight states?

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/View/StartChatSuggestedUserCell.swift
> +                let firstRowText = displayName.isEmpty ? user.userId : displayName
This logic feels a bit convoluted, I would just simply drop everything in the Text() i.e. `Text(user.displayName.isEmpty ? user.userId : user.displayName)`

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/View/StartChatSuggestedUserCell.swift
> +                Text(secondRowText)
Same comment as above and you should probably center things vertically when the second line is missing. Looks a bit weird otherwise

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +    func currentDirectRoomWithUser(_ userId: String) async -> Result<String?, ClientProxyError> {
What does "current" mean in this context? In keeping with the name of `roomForIdentifier` can we maybe call this `directRoomForUserIdentifier`?

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Services/Room/RoomMemberProxy.swift
> +    // convenience init for start chat flow while a proper User Struct is missing from search result
A `convenience` constructor without a `convenience` specifier? 😅 I don't think we need this comment, just having the constructor in here is clear enough, no matter where it's used from.

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatCoordinator.swift
> +                    let currentDirectRoom = await self.parameters.userSession.clientProxy.currentDirectRoomWithUser(user.userId)
Don't you need some sort of loading indicator to block interaction while these potentially long taks running? same for creating a room

2023-03-22 10:58 UTC, stefanceriu commented on ElementX/Sources/Services/UserSession/UserSessionFlowCoordinator.swift
> +                self.presentRoomWithIdentifier(identifier)
This is wrong, room presentation should go through state machine changes not be invoked directly i.e. `stateMachine.processEvent(.selectRoom(roomId: roomId))` the same as we do for `case .presentRoom`. Otherwise you will leave the state machine in an inconsistent state and it will crash

2023-03-22 13:37 UTC, alfogrillo commented on ElementX/Sources/Screens/StartChat/StartChatCoordinator.swift
>                  // TODO: start create room flow
What are people using to mark spots in the code where future developments are required in the near future?

2023-03-22 13:47 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatCoordinator.swift
>                  // TODO: start create room flow
Nothing, chances are 3 years down the line you're going to end up with a ton of TODO's that don't make sense to anybody. If you, for example, have an enum case that's not handled just break on it. It would be very clear to everybody that nothing is happening there and if you do need to come back to it I'm sure it's going to be easy enough to find out without a TODO. If it's not then we're probably doing something wrong

2023-03-22 13:58 UTC, alfogrillo commented on ElementX/Sources/Screens/StartChat/StartChatCoordinator.swift
> +            case .userSelected(let user):
I think we won't use real "members" in the near future, since here is when we are creating rooms so there isn't any membership concept involved yet.

2023-03-22 13:58 UTC, alfogrillo commented on ElementX/Sources/Screens/StartChat/StartChatModels.swift
> +    var searchedUsers: [RoomMemberProxy] = []
To clarify: this is a mock. I think we are going to use [this type](https://github.com/matrix-org/matrix-rust-sdk/pull/1689/files#diff-f4219660dd4687809f8c9f0a5f4f17b5e782ea7e28f5b6e40cccbb67c38e1308R552) (or a proxy of it) instead.
Does it make sense to updated here since the above has been released already?

2023-03-22 14:00 UTC, alfogrillo commented
@flescio you can use the same pattern for naming the branches we had on Element.
eg. `flescio/show_or_create_dm` instead of `epic/create_and_join_rooms`.
No need to change it here imho.

2023-03-23 08:41 UTC, flescio commented on ElementX/Sources/Screens/StartChat/StartChatCoordinator.swift
> +                    let currentDirectRoom = await self.parameters.userSession.clientProxy.currentDirectRoomWithUser(user.userId)
@stefanceriu  Since I moved this logic to the viewModel, in order to use the indicator, should I expose the userIndicatorController to the viewModel, or should I create 2 actions inside StartChatViewModelAction like showIndicator and hideIndicator, so the coordinator will be in charge of that?

2023-03-23 14:22 UTC, stefanceriu approved these changes
Looks good to me, nicely done!

2023-03-23 14:22 UTC, stefanceriu commented on ElementX/Sources/Other/SwiftUI/List Styles/ListSection.swift
> +struct ListSectionStyle: ViewModifier {
Same comment as above

2023-03-23 16:01 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChat/StartChatModels.swift
> +    var suggestedUsers: [UserProfileProxyProtocol] = [UserProfileProxyMock.mockAlice, UserProfileProxyMock.mockBob, UserProfileProxyMock.mockCharlie]
Then maybe you should create a Section struct that has the title and an `UserProfileProxyProtocol` array?

2023-03-23 16:06 UTC, pixlwave commented on ElementX/Sources/Other/SwiftUI/List Styles/ListRow.swift
> +    static let insets = EdgeInsets(top: 10, leading: 16, bottom: 10, trailing: 16)
Eventually yes, but we'll be doing that screen by screen and moved stuff as we need it so for now, this is fine.

The comment should say all our `List` rows though 😜

2023-03-23 16:38 UTC, pixlwave reviewed
Had a quick skim through whilst I was here and added a couple of tiny comments :)

2023-03-23 16:38 UTC, pixlwave commented on ElementX/Sources/Services/Users/UserProfile.swift
> +    var userId: String { get }
```suggestion
    var userID: String { get }
```

2023-03-23 16:38 UTC, pixlwave commented on ElementX/Sources/Services/Client/ClientProxyProtocol.swift
> +    func createDirectRoom(with userId: String) async -> Result<String, ClientProxyError>
```suggestion
    func directRoomForUserID(_ userID: String) async -> Result<String?, ClientProxyError>
    
    func createDirectRoom(with userID: String) async -> Result<String, ClientProxyError>
```

2023-03-23 16:38 UTC, pixlwave commented on ElementX/Sources/Screens/StartChat/StartChatViewModel.swift
> +            .debounce(for: .milliseconds(300), scheduler: DispatchQueue.main)
Should there be a `removeDuplicates` in here too? That would make sure not to call the closure when
a) The user types and then removes a character in the search field within the debounce time, leaving the query unchanged.
b) Any other part of the view state is updated that isn't the search query.

2023-03-23 16:38 UTC, pixlwave commented on ElementX/Sources/Screens/StartChat/StartChatViewModel.swift
> +            })
Can we prefer trailing closures please?
```suggestion
            .sink { [weak self] searchQuery in
                if MatrixEntityRegex.isMatrixUserIdentifier(searchQuery) {
                    self?.state.searchResults = [UserProfileProxy(userId: searchQuery, displayName: nil, avatarURL: nil)]
                } else {
                    self?.state.searchResults = []
                }
            }
```

2023-03-24 11:15 UTC, pixlwave approved these changes
Nice!

2023-03-24 11:15 UTC, pixlwave commented on ElementX/Sources/Screens/StartChat/StartChatViewModel.swift
> +            .removeDuplicates()
Sorry my bad, my comment was very specific. You want this *after* the debounce I believe.

2023-03-24 11:23 UTC, flescio commented on ElementX/Sources/Screens/StartChat/StartChatViewModel.swift
> +            .removeDuplicates()
You're right, I also got it wrong

2023-03-24 14:05 UTC, alfogrillo commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +    }
We can make it a bit more readable
```suggestion
    func directRoomForUserID(_ userID: String) async -> Result<String?, ClientProxyError> {
        await Task.dispatch(on: clientQueue) {
            do {
                let room = try self.client.getDmRoom(userId: userID)?.id()
                return room.map { .success($0) } ?? .success(nil)
            } catch {
                return .failure(.failedRetrievingDirectRoom)
            }
        }
    }
```

2023-03-24 14:05 UTC, alfogrillo commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +                let parameters = CreateRoomParameters(name: "", topic: nil, isEncrypted: true, isDirect: true, visibility: .private, preset: .privateChat, invite: [userID], avatar: nil)
```suggestion
                let parameters = CreateRoomParameters(name: "", topic: nil, isEncrypted: true, isDirect: true, visibility: .private, preset: .trustedPrivateChat, invite: [userID], avatar: nil)
```

I think trusted private chat is the default on Element legacy. Please have a look there. 
I think it makes more sense.

2023-03-24 14:05 UTC, alfogrillo commented on ElementX/Sources/Services/Users/UserProfile.swift
> +struct UserProfileProxy: UserProfileProxyProtocol {
I don't think we need `UserProfileProxyProtocol`.  `struct UserProfileProxy` should be enough.

2023-03-24 14:57 UTC, alfogrillo approved these changes
LGTM! 🎉

2023-03-24 15:16 UTC, merged