Add Block user to Report Content screen.
vector-im/element-x-ios pull request #742
Opened 2023-03-29 13:16 UTC by pixlwave

This PR adds the Block user toggle to the Report Content screen. It additionally adopts compound-ios for the screen as it is the same as the Bug Report screen so can use all the existing tokens/styles.

Draft for now until we have an SDK release containing https://github.com/matrix-org/matrix-rust-sdk/pull/1713

| Initial State | With Report |
| - | - |
| ![Simulator Screen Shot - iPhone 14 - 2023-03-29 at 13 08 19](https://user-images.githubusercontent.com/6060466/228549786-4ee1936f-71b1-4d00-a647-a8bf73cc206f.png) | ![Simulator Screen Shot - iPhone 14 - 2023-03-29 at 14 14 56](https://user-images.githubusercontent.com/6060466/228549798-fbe955f8-c5c8-4ae2-a0a8-e5797cf179e2.png) |

### Pull Request Checklist

- [ ] I read the [contributing guide](https://github.com/vector-im/element-ios/blob/develop/CONTRIBUTING.md)
- [ ] Pull request contains a [changelog file](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#changelog) in ./changelog.d
- [ ] Pull request includes a [sign off](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#sign-off)

**UI changes have been tested with:**
- [ ] iPhone and iPad simulators in portrait and landscape orientations.
- [ ] Dark mode enabled and disabled.
- [ ] Various sizes of dynamic type.
- [ ] Voiceover enabled.

2023-03-31 10:55 UTC, pixlwave commented
Still needs an update to the SDK, but marking as ready for review given the `room.ignore` method is now merged.

2023-03-31 11:18 UTC, pixlwave commented on UITests/Sources/__Snapshots__/Application/pseudo-iPhone-14.reportContent-1.png
It is for now (its worse on dark mode where its a white toggle on an almost white background) - the Toggle style hasn't been confirmed yet on compound, but we can update it as soon as it has.

2023-03-31 11:21 UTC, Velin92 commented on ElementX/Sources/Services/Room/RoomProxy.swift
> +    func reportContent(_ eventID: String, reason: String?, ignoring senderID: String? = nil) async -> Result<Void, RoomProxyError> {
you know what... actually instead of having `reportContent(eventID, reason, senderID)` at this point maybe I would prefer to mirror the SDK and have two functions `reportContent` and `ignoreUser`.
For two reasons:
- this ignoreUser function is quite useful, and may be useful also for my current DM Work, and for the future when we implement the unblock function on the blocked composer for blocked users
- In this way in case one errors out and the other one does not, we can display an error message saying x was sucessfull but y was not.

Ofc for now we only have the ignore exposed on the room, and not the unignore but it could a start. WDYT?

2023-03-31 11:23 UTC, Velin92 commented on ElementX/Sources/Services/Room/RoomProxy.swift
> +    func reportContent(_ eventID: String, reason: String?, ignoring senderID: String? = nil) async -> Result<Void, RoomProxyError> {
Also is worth testing what could happen if you ignore an already ignored user... prolly nothing but who knows

2023-03-31 11:23 UTC, pixlwave commented on ElementX/Sources/Services/Room/RoomProxy.swift
> +    func reportContent(_ eventID: String, reason: String?, ignoring senderID: String? = nil) async -> Result<Void, RoomProxyError> {
Sure thing, makes sense to me, I'll update 👍

2023-03-31 11:33 UTC, Velin92 requested changes
I would maybe prefer to have ignore and reportContent as separate functions at this point

2023-04-03 07:39 UTC, pixlwave commented on UnitTests/Sources/ReportContentViewModelTests.swift
> +        roomProxy.reportContentReasonIgnoringReturnValue = .success(())
We discussed this and decided it wasn't useful in this instance.

2023-04-03 07:43 UTC, pixlwave commented on UnitTests/Sources/MediaProvider/MediaLoaderTests.swift
> +    func getProfile(userId: String) throws -> MatrixRustSDK.UserProfile { fatalError() }
Seems this was missed with the latest SDK update.

2023-04-03 07:57 UTC, Velin92 approved these changes

2023-04-03 09:17 UTC, Velin92 commented
maybe we want to change the loading screen to be less of a blocker for the user UI? not required to do in this PR

2023-04-03 09:21 UTC, merged