DM Details View
vector-im/element-x-ios pull request #744
Opened 2023-03-29 19:16 UTC by Velin92

2023-03-30 09:10 UTC, callumu commented
I realised that we're changing slightly how share and copy link are shown, and aligning it with web. As after selecting 'share' there is an option to copy the link, we decided to remove the 'Copy link' option from everywhere and change 'Share room' or 'Invite' to just 'Share'.

The updated designs are on this page: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=5%3A7388

2023-03-31 06:12 UTC, stefanceriu requested changes
Good start, I've left some comment inline 👍

2023-03-31 06:12 UTC, stefanceriu commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsViewModel.swift
> +            state.dmRecipient?.isIgnored = true
I dislike the fact that ignore requests are done directly through the `RoomMemberProxy` and that `RoomProxy` members are left in an inconsistent state. Ideally a successful (un)ignore should inform the `RoomProxy` which would publish the members again, which would then update the `RoomDetailsViewModel` members and implicitly the UI. There should be no need to manually set any bool on the `RoomMemberDetails`

2023-03-31 06:12 UTC, stefanceriu commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsModels.swift
> +    var dmRecipient: RoomMemberDetails? {
Can we merge `isDMRoom` with `dmRecipient`? Can you even have a dmRoom without a recipient?

2023-03-31 06:12 UTC, stefanceriu commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsModels.swift
> +    var dmRecipient: RoomMemberDetails? {
Also, is `recipient` the right name here? Maybe `counterpart` or `interlocutor` works better

2023-03-31 08:36 UTC, Velin92 commented on ElementX/Sources/Other/SwiftUI/Views/HeaderView.swift
> +struct HeaderView<Actions: View>: View {
the thing is that is also used as `RoomHeaderView` uhm... what about simply `AvatarHeaderView` ?

2023-03-31 08:38 UTC, Velin92 commented on ElementX/Sources/Other/SwiftUI/Views/HeaderView.swift
> +                .accessibilityIdentifier(accessibilityIdentifier ?? "")
I see that we only use it for one instance which is the RoomDetailsView, and it has a specific name related for that use case, but maybe we can scrap that and have only a single one? Or maybe I could rework that test to see if we could append the accessibilityIdentifier to the whole `HeaderView`?

2023-03-31 08:43 UTC, Velin92 commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsViewModel.swift
> +            state.dmRecipient?.isIgnored = true
the thing is that I would like to avoid to fetch all the members again with the populateMembers function... however I have an idea... I could see if I could expose a function that only fetches one single member state given their id... so if the state changes, we just fetch that single RoomMember back here.

I am pretty sure we already have something like that in the SDK, and that I just need to expose it in FFI.

Is it something I should do immediately? or is it fin to keep it as it is for now and release an improvement PR later (which hopefully would also include the sync `active_members_count`)?

2023-03-31 08:46 UTC, Velin92 commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsModels.swift
> +    var dmRecipient: RoomMemberDetails? {
I mean yeah i could change that however I feel recipient is the most appropriate name, since it identifies the person that is receiving the message in a mail/messages exchange.

2023-03-31 08:48 UTC, Velin92 commented on ElementX/Sources/Screens/HomeScreen/HomeScreenCoordinator.swift
> +            genericRoomViewModel.presentCrashedLastRunAlert()
weird... don't remember to have changed this, must have been a renaming issue will revert this.

2023-03-31 08:49 UTC, Velin92 commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsModels.swift
> +        isEncrypted && isDirect && members.count == 2
Specification: https://github.com/vector-im/element-meta/issues/1167

2023-03-31 08:50 UTC, Velin92 commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsModels.swift
> +    struct IgnoreUserAlertItem: AlertItem, Equatable {
because I reuse this same name in `RoomMemberDetailsViewStateBindings`

2023-03-31 08:53 UTC, Velin92 commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsModels.swift
> +        set {
it's to allow for this: `state.dmRecipient?.isIgnored = true`
However maybe I could create a function that does this and call it `setDmRecipientIsIgnored(_ Bool)` 
Or... if I expose a function to update the RoomMember directly from ffi this should not be needed at all.

2023-03-31 10:51 UTC, stefanceriu commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsModels.swift
> +    struct IgnoreUserAlertItem: AlertItem, Equatable {
Right, gotcha 👍

2023-03-31 10:54 UTC, stefanceriu commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsViewModel.swift
> +            state.dmRecipient?.isIgnored = true
Another option would be to store and update them client side and only delegate back when you know they changed.

I'm not going to push for it now but **we do** need to make sure this happens in order to avoid tricky errors. Any change to a member's fields should be propagated through the room proxy publisher

2023-03-31 10:54 UTC, stefanceriu commented on ElementX/Sources/Screens/RoomDetails/RoomDetailsModels.swift
> +    var dmRecipient: RoomMemberDetails? {
Fair 👍

2023-03-31 11:52 UTC, Velin92 commented on ElementX/Sources/Services/Room/RoomProxyProtocol.swift
> +    func populateMembers() async
we already have a function a private function that is called fetchMembers... which fetches the members for real and populates them only in the db... so I am wondering if I should actually call this `updateMembers()`?

2023-03-31 12:06 UTC, stefanceriu commented on ElementX/Sources/Services/Room/RoomProxyProtocol.swift
> +    func populateMembers() async
Oh right, yeah `updateMembers` works nicely

2023-04-03 11:18 UTC, merged