Select members before creating a room (UI for selection)
vector-im/element-x-ios pull request #766
Opened 2023-04-05 08:15 UTC by flescio

Add screen for inviting users

2023-04-05 15:38 UTC, pixlwave requested changes
Nice, its great to start seeing this flow 😎

I've added some initial comments, I think it will probably create enough changes to make it a first round for review if that's ok?

2023-04-05 15:38 UTC, pixlwave commented on ElementX/Sources/Screens/StartChat/StartChatCoordinator.swift
> +                self.presentInviteUsersScreen()
I wonder if we should add a comment here to say that before creating a room we select the users we would like to invite? Because the mapping of the `.createRoom` action to presenting the `InviteUsersScreen` feels like an error until you look at the designs on Figma.

2023-04-05 15:38 UTC, pixlwave commented on UITests/Sources/InviteUsersInRoomScreenUITests.swift
> +    }
Do you think it would be a good idea to make another snapshot test here with a couple of selected users?

2023-04-06 07:44 UTC, flescio commented on ElementX/Sources/Screens/InviteUsersInRoom/InviteUsersInRoomCoordinator.swift
I wanted to differentiate a little from the current InviteFriends, which has nothing to do with rooms invitations. But yeah your observation is valid, should I change it?

2023-04-06 07:45 UTC, flescio commented on ElementX/Sources/Screens/InviteUsersInRoom/InviteUsersInRoomModels.swift
> +    var scrollToLastIDPublisher: String?
my bad, I tried with a Publisher first, and forgot to rename it

2023-04-06 07:51 UTC, flescio commented on ElementX/Sources/Screens/InviteUsersInRoom/InviteUsersInRoomModels.swift
> +    var usersSection: StartChatUsersSection = .init(type: .suggestions, users: [])
the selectedUsers refer to users selected and to the horizontal carousel, instead the section is needed because it will provide the suggestion layout OR the search results layout. Probably its better to use this type, but renaming it with something more generic.

2023-04-06 07:54 UTC, flescio commented on ElementX/Sources/Screens/InviteUsersInRoom/InviteUsersInRoomModels.swift
> +    case proceed
I choose that because it can also be used with the "Skip" action, simply we move forward with an empty array,
we are not submitting anything yet and next can be confusing

2023-04-06 09:27 UTC, pixlwave commented on ElementX/Sources/Screens/InviteUsersInRoom/InviteUsersInRoomModels.swift
> +    var usersSection: StartChatUsersSection = .init(type: .suggestions, users: [])
Riiight, ok understood 👍

2023-04-06 09:36 UTC, pixlwave commented on ElementX/Sources/Screens/InviteUsersInRoom/InviteUsersInRoomCoordinator.swift
Yes please. I would like to remove the `InviteFriendsCoordinator` and replace it with a `ShareLink` like we do in the room/member details screens tbh. Might do that now whilst I think about it.

2023-04-08 09:44 UTC, ifeeltiredboss commented
What's the purpose of showing the avatars on horizontal scrollable pane? Isn't it just duplication of information?

2023-04-11 12:06 UTC, pixlwave reviewed
Thanks, the refactor to `InviteUsersXYZ` makes this much cleaner 🙏

Nothing major now, just general comments :)

2023-04-11 12:06 UTC, pixlwave commented on ElementX/Sources/Screens/InviteUsers/View/SelectedInvitedUserItem.swift
> +            Text(user.displayName ?? user.userID)
Wonder if you might want
a) a `lineLimit` on this Text
b) To set the `VStack` alignment to `.top` so that the avatars all remain aligned when a user has a long displayname.

2023-04-11 12:06 UTC, pixlwave commented on ElementX/Sources/Screens/StartChat/StartChatModels.swift
> +struct SearchUsersUsersSection {
Not sure where these should live, but it probably isn't inside of `StartChatModels` following the rename.

2023-04-12 08:23 UTC, flescio commented on UnitTests/Sources/InviteUsersViewModelTests.swift
> +        viewModel.state.usersSection = .init(type: .suggestions, users: [.mockAlice, .mockBob, .mockCharlie])
will do with the next feature about the UsersProvider service

2023-04-13 14:19 UTC, flescio commented on ElementX/Sources/Screens/InviteUsers/View/SelectableUserCell.swift
VoiceOver works not quite as a on off toggle, but it says clearly "selected" when selected or button when not selected

2023-04-14 09:02 UTC, pixlwave approved these changes
LGTM 👏

2023-04-14 09:02 UTC, pixlwave commented on ElementX/Sources/Screens/InviteUsers/View/InviteUsersScreen.swift
> +                .buttonStyle(FormButtonStyle(accessory: .selection(isSelected: context.viewState.selectedUsers.contains { $0.userID == user.userID })))
Optional: A small nicety for tidyness would be to put this logic in a method the state so you could
```suggestion
                .buttonStyle(FormButtonStyle(accessory: .selection(isSelected: context.viewState.isUserSelected(user)))
```

2023-04-14 09:21 UTC, alfogrillo approved these changes
LGTM, just left minor comments

2023-04-14 09:21 UTC, alfogrillo commented on ElementX/Sources/Screens/InviteUsers/InviteUsersCoordinator.swift
> +    private var viewModel: InviteUsersViewModelProtocol
```suggestion
    private let viewModel: InviteUsersViewModelProtocol
```

2023-04-14 09:21 UTC, alfogrillo commented on ElementX/Sources/Screens/InviteUsers/View/InviteUsersScreen.swift
> +struct InviteUsers_Previews: PreviewProvider {
```suggestion
struct InviteUsersScreen_Previews: PreviewProvider {
```

2023-04-14 09:21 UTC, alfogrillo commented on ElementX/Sources/Screens/InviteUsers/View/InviteUsersSelectedItem.swift
> +struct SelectedInvitedUserItem_Previews: PreviewProvider {
```suggestion
struct InviteUsersSelectedItem_Previews: PreviewProvider {
```

2023-04-14 09:21 UTC, alfogrillo commented on ElementX/Sources/Screens/SearchUsersSection/SearchUsersCell.swift
> +struct SearchUsersCell: View {
`UserProfileCell` would be better to me

2023-04-14 09:21 UTC, alfogrillo commented on UITests/Sources/__Snapshots__/Application/pseudo-iPhone-14.inviteUsers-1.png
Not sure why we see Italian here 🤔

2023-04-17 08:29 UTC, merged