Accept and decline invites
vector-im/element-x-ios pull request #806
Opened 2023-04-17 14:51 UTC by alfogrillo

Fixes https://github.com/vector-im/element-x-ios/issues/621

2023-04-18 10:16 UTC, alfogrillo commented on UITests/Sources/__Snapshots__/Application/pseudo-iPhone-14.invites-1.png
Idk what's happening here (didn't investigate yet):

- Some keys aren't resolved
- Some text is in Italian

Any idea?

2023-04-18 10:35 UTC, pixlwave commented on UITests/Sources/__Snapshots__/Application/pseudo-iPhone-14.invites-1.png
- First one should be fixed on `develop` now 🤞
- Second one I think we need to make sure the device's language list is English and English alone so it matches the default config:
![Simulator Screenshot - iPhone 14 Pro - 2023-04-18 at 11 34 19](https://user-images.githubusercontent.com/6060466/232751541-33c3e99d-afe2-4b64-92d2-5d8335729dec.png)

2023-04-18 13:20 UTC, alfogrillo commented on UITests/Sources/__Snapshots__/Application/pseudo-iPhone-14.invites-1.png
> First one should be fixed on develop now 

It worked! 🎉

> Second one I think we need to make sure the device's language list is English and English alone so it matches the default config:

I expected the language in the test plan to override the simulator one. But it looks not working for the pseudo language I guess. 🤔
The workaround you suggested worked anyway. 👍🏻

2023-04-19 09:44 UTC, stefanceriu requested changes

2023-04-19 09:44 UTC, stefanceriu commented on ElementX/Sources/Services/UserSession/UserSessionFlowCoordinatorStateMachine.swift
> +        case invitesScreen(selectedRoomId: String?, shownRoomId: String?)
What's the difference between the `selectedRoomId` and the `shownRoomId`? 🤔

2023-04-19 10:32 UTC, alfogrillo commented on ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
> +                                         isDirect: fullRoom?.isDirect() ?? room.isDm() ?? false,
We have now a custom logic in the sdk for the `isDirect` flag for rooms in the invite state.
This logic is available on a `Room`. More context [here](https://github.com/matrix-org/matrix-rust-sdk/pull/1775).

2023-04-19 10:39 UTC, alfogrillo commented on ElementX/Sources/Services/UserSession/UserSessionFlowCoordinator.swift
> +                    let .invitesScreen(_, selectedRoomId) where selectedRoomId == roomIdentifier:
Not really: as described [here](https://github.com/vector-im/element-x-ios/pull/806#discussion_r1171151338) the actual timeline in case of invites is the second component, the first one is there just to fix the above mentioned technical problem.
If this is confusing I can add two separate cases (doing the same thing though).

2023-04-19 11:22 UTC, stefanceriu commented on ElementX/Sources/Services/UserSession/UserSessionFlowCoordinatorStateMachine.swift
> +        case invitesScreen(selectedRoomId: String?, shownRoomId: String?)
Talked about this offline: we will try to simplify the logic by replacing the currently selected room with the one that needs to be opened after accepting an invititation.

2023-04-19 13:35 UTC, alfogrillo commented on ElementX/Sources/Services/UserSession/UserSessionFlowCoordinatorStateMachine.swift
> +        case invitesScreen(selectedRoomId: String?, shownRoomId: String?)
Done here -> https://github.com/vector-im/element-x-ios/pull/806/commits/a166bc67fd7713f344540595d8fa138ed468a046

2023-04-19 14:22 UTC, stefanceriu approved these changes
Great stuff 👌

2023-04-19 15:05 UTC, merged