Fix: forget the user’s consents for analytics on logout
vector-im/element-x-ios pull request #816
Opened 2023-04-20 13:31 UTC by nimau

This PR reset the user's consents for analytics on logout (as requested in #106)

2023-04-20 15:26 UTC, stefanceriu requested changes

2023-04-20 15:26 UTC, stefanceriu commented on ElementX/Sources/Application/AppSettings.swift
> +    static func forgetAnalyticsConsents() {
@pixlwave and I were chatting about this and we believe we have a better solution:
- change `enableAnalytics` to be an enum with 3 values stored as a RawRepresentable with a default value of `.unknown` or similar
- remove the `forgetAnalyticsConsents` and just use `ServiceLocator.shared.settings.enableAnalytics  = .unknown` when you want to reset it

2023-04-21 14:26 UTC, nimau commented on ElementX/Sources/Application/AppSettings.swift
> +    static func forgetAnalyticsConsents() {
Hi @stefanceriu, I've updated the PR to reflect this change.
Also I took the liberty of renaming the UserDefaultKey from `enableAnalytics` to `analyticsConsentState` to better reflect the purpose of this key.

2023-04-21 14:28 UTC, stefanceriu approved these changes
Looks great 👍

2023-04-21 14:28 UTC, stefanceriu commented on ElementX/Sources/Services/Analytics/AnalyticsConsentState.swift
> +    case optIn
Should these be called `optedIn` and `optedOut` maybe?

2023-04-21 14:28 UTC, stefanceriu commented on ElementX/Sources/Application/AppCoordinator.swift
> +            ServiceLocator.shared.analytics.resetConsentState()
At this point wouldn't it be better to keep the `reset` method that would `optOut` + `resetConsent` internally?

2023-04-21 14:48 UTC, nimau commented on ElementX/Sources/Services/Analytics/AnalyticsConsentState.swift
> +    case optIn
Done.

2023-04-21 14:51 UTC, nimau commented on ElementX/Sources/Application/AppCoordinator.swift
> +            ServiceLocator.shared.analytics.resetConsentState()
There is a `reset` method on `Analytics` but it is for resetting the analytics client and the bug report service. Do you mean to move these two calls inside a new private `reset` method inside the `AppCoordinator`?

2023-04-21 14:52 UTC, stefanceriu commented on ElementX/Sources/Application/AppCoordinator.swift
> +            ServiceLocator.shared.analytics.resetConsentState()
No no, sorry, I didn't realise there's another reset method in there

2023-04-21 15:05 UTC, merged