Create a room screen (UI only)
vector-im/element-x-ios pull request #877
Opened 2023-05-11 10:37 UTC by flescio

Add the create room screen, UI only, picking the room image or actually creating a room are out of scope.

![Simulator Screenshot - iPhone 14 Pro - 2023-05-11 at 12 29 19](https://github.com/vector-im/element-x-ios/assets/20090282/fc39c4d0-6e02-44aa-97a4-66cbb98c64e9)

2023-05-12 09:39 UTC, stefanceriu requested changes
Nice one! I left some comments inline

2023-05-12 09:39 UTC, stefanceriu commented on ElementX/Sources/Other/AccessibilityIdentifiers.swift
> +        let roomTopic = "create-room-room-topic"
These are not respecting the existing format. They're supposed to be `create_room-room_name` and `create_room-room_topic` or even `create_room-name` and `create_room-topic`

2023-05-12 09:39 UTC, stefanceriu commented on ElementX/Sources/Screens/CreateRoom/CreateRoomViewModel.swift
> +                self?.createRoomParameters.isRoomPrivate = bindings.isRoomPrivate
Why do you need to store these every time they update? You should just compute them before calling back with the creation action i.e. `.createRoom(parameters)` instead of sharing state

2023-05-12 09:39 UTC, stefanceriu commented on ElementX/Sources/Screens/CreateRoom/View/CreateRoomScreen.swift
> +    @ScaledMetric private var roomIconSide: CGFloat = 64
Presumably this is supposed to be `roomIconSize`

2023-05-12 09:39 UTC, stefanceriu commented on ElementX/Sources/Screens/CreateRoom/View/CreateRoomScreen.swift
> +    @ScaledMetric private var cellWidth: CGFloat = 64
Let's rename `cellWidth` to someting more appropriate like `invitedUserCellWidth`

2023-05-12 09:39 UTC, stefanceriu commented on ElementX/Sources/Screens/CreateRoom/View/CreateRoomScreen.swift
> +    }
Do we really need these single line methods? Don't feel like they bring any value

2023-05-12 09:39 UTC, stefanceriu commented on ElementX/Sources/Screens/SessionVerificationScreen/SessionVerificationScreenViewModel.swift
> +                    }
I think this one we can just ignore instead of printing the localized description

2023-05-12 09:39 UTC, stefanceriu commented on ElementX/Sources/Screens/StartChatScreen/StartChatScreenCoordinator.swift
> +    private var createRoomParameters = CreateRoomVolatileParameters()
Instead of modifying this from multiple places we should just pass it back and forth. It's simpler to reason about and generally leads to less problems

2023-05-12 09:39 UTC, stefanceriu commented on UITests/Sources/CreateRoomScreenUITests.swift
> +        }
Why does it matter what kind of user interface we're running, can't we just use the same very long name for both? 🤔

2023-05-12 09:39 UTC, stefanceriu commented on UnitTests/Sources/CreateRoomViewModelTests.swift
> +        context.send(viewAction: .selectPrivateRoom)
Aren't you supposed to `await context.nextViewState()` before asserting these? 🤔

2023-05-12 09:39 UTC, stefanceriu commented on ElementX/Sources/Screens/CreateRoom/View/CreateRoomScreen.swift
> +            .buttonStyle(FormButtonStyle(iconAlignment: .top, accessory: .singleSelection(isSelected: context.isRoomPrivate)))
Any chance we can remove the animations from these, it doesn't look right at all?

2023-05-12 12:17 UTC, flescio commented on UITests/Sources/CreateRoomScreenUITests.swift
> +        }
If you don't see any other problem, I made it like this because it's really time consuming.

2023-05-12 14:23 UTC, alfogrillo commented on ElementX/Sources/Screens/CreateRoom/CreateRoomViewModel.swift
> +                self?.createRoomParameters.isRoomPrivate = bindings.isRoomPrivate
I think this is for sharing a draft state with `InviteUsersScreenCoordinator`.
@flescio I was thinking: is it better if we read the draft state in `InviteUsersScreenCoordinator` when a `CreateRoomCoordinator` is popped back?

2023-05-12 14:23 UTC, alfogrillo commented on ElementX/Sources/Screens/CreateRoom/View/CreateRoomScreen.swift
> +    private var selectedUsersSection: some View {
```suggestion

    private var selectedUsersSection: some View {
```

2023-05-12 14:23 UTC, alfogrillo commented on ElementX/Sources/Screens/InviteUsersScreen/InviteUsersScreenCoordinator.swift
> +        let paramenters = CreateRoomCoordinatorParameters(userSession: parameters.userSession, createRoomParameters: createRoomParameters)
```suggestion
        let parameters = CreateRoomCoordinatorParameters(userSession: parameters.userSession, createRoomParameters: createRoomParameters)
```

2023-05-12 14:23 UTC, alfogrillo commented on ElementX/Sources/Screens/InviteUsersScreen/InviteUsersScreenCoordinator.swift
> +            default:
```suggestion
            case .createRoom:
```

2023-05-12 14:23 UTC, alfogrillo commented on ElementX/Sources/Screens/InviteUsersScreen/InviteUsersScreenCoordinator.swift
> +        parameters.navigationStackCoordinator?.push(coordinator)
```suggestion
        .store(in: &cancellables)

        parameters.navigationStackCoordinator?.push(coordinator)
```

2023-05-12 14:23 UTC, alfogrillo commented on ElementX/Sources/Services/CreateRoom/CreateRoomParameters.swift
> +class CreateRoomVolatileParameters {
```suggestion
class CreateRoomFlowState {
```

2023-05-12 14:23 UTC, alfogrillo commented on UITests/Sources/CreateRoomScreenUITests.swift
> +        }
I think Stefan is asking why we don't have the longest string on both iPhone/iPad.

2023-05-12 14:23 UTC, alfogrillo commented on UITests/Sources/__Snapshots__/Application/en-GB-iPad-9th-generation.createRoom-2.png
Italian keyboard. Probably keyboard should be dismissed whenever is possible.

2023-05-12 17:08 UTC, pixlwave reviewed
Not a proper review, just looked at the screenshot and noticed the following:

2023-05-12 17:08 UTC, pixlwave commented on ElementX/Sources/Screens/CreateRoom/View/CreateRoomScreen.swift
> +            Text(L10n.screenCreateRoomTopicLabel)
```suggestion
            Text(L10n.screenCreateRoomTopicLabel)
                .formSectionHeader()
```

2023-05-12 17:08 UTC, pixlwave commented on ElementX/Sources/Screens/CreateRoom/View/CreateRoomScreen.swift
> +            Text(L10n.commonSecurity.uppercased())
I don't think the `.uppercased()` is needed here, the default style does that automatically right?
```suggestion
            Text(L10n.commonSecurity.uppercased())
                .formSectionHeader()
```

2023-05-15 10:18 UTC, stefanceriu approved these changes
Looks good to me, nicely done 👏

2023-05-16 16:23 UTC, merged