Cleanup the background task that pauses the SDK when resigning active
vector-im/element-x-ios pull request #903
Opened 2023-05-16 16:21 UTC by Velin92

2023-05-16 16:22 UTC, Velin92 commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +            while !slidingSyncObserverToken.isFinished() { }
not super elegant I know, but as of right now we don't have callbacks that tell us when a TaskHandle has finished

2023-05-17 09:08 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +            while !slidingSyncObserverToken.isFinished() { }
I wonder if we could benefit from exposing another rust Client delegate method to let us know when this is done 🤔

2023-05-17 10:45 UTC, stefanceriu commented on ElementX/Sources/Application/AppCoordinator.swift
> +                guard let self else { return }
I wonder if running this later might cause problems if quickly backgrounding and foregrounding the app, problems like `startSync` failing

2023-05-17 15:54 UTC, Velin92 commented
I am actually wondering, do we really need this background task at all? Don't we just need to suspend the sync when the AppCoordinator sees that the app is suspending, and nothing more?

2023-05-17 15:59 UTC, Velin92 commented on ElementX/Sources/Application/AppCoordinator.swift
> +                guard let self else { return }
should have solved this in the last commit

2023-05-19 06:09 UTC, stefanceriu requested changes
Looks good to me but I would like some api changes that I commented on inline.

Separately from this, the usage of the background tasks in the roomProxy feels fishy to me. For example `sendMessage` starts a background task and then stops it on exiting the method. In reality the async call to the SDK doesn't return when the message was actually sent but when it was enqueued. I think that basically means that the background task here is useless. What do you think?

2023-05-19 06:09 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +        stopSync()
Can we not merge these 2 stopSyncs into one? 🤔 If not we should at least make one of them private

2023-05-19 06:09 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +    var isSyncing: Bool {
Wouldn't it be cleaner if this check was done internal to the ClientProxy and it would result in a no-op if already syncing or already not syncing?

startSync already has a check for this

```
MXLog.info("Starting sync")
        guard slidingSyncObserverToken == nil else {
            return
        }
```

2023-05-19 07:37 UTC, Velin92 commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +    var isSyncing: Bool {
the problem is that the startSync() implementation inside the AppCoordinator, which has code that runs regardless of such state

2023-05-19 07:54 UTC, Velin92 commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +        stopSync()
the problem is that optional closures are automatically marked as @escaping, and since escaping closure are slightly slower than non escaping closure (and the expiration handler needs to complete ASAP), I don't want to create a function that uses an optional closure. It's a very minor optimisation honestly, but I would like to keep it just fort his specific bg case (I wrote a doc about this verison of the function) since we are still running a while loop which could take 1 second at most.

2023-05-19 08:03 UTC, Velin92 commented
> Looks good to me but I would like some api changes that I commented on inline.
> 
> Separately from this, the usage of the background tasks in the roomProxy feels fishy to me. For example `sendMessage` starts a background task and then stops it on exiting the method. In reality the async call to the SDK doesn't return when the message was actually sent but when it was enqueued. I think that basically means that the background task here is useless. What do you think?

I actually tested it and the background task is actually needed,  I added an artificial  delay before the enqueueing of let's say 3 seconds before the sending of the message, without that bg task it will only get sent when I relaunch the app.

2023-05-19 08:12 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +        stopSync()
Okay, fair enough

2023-05-19 08:13 UTC, stefanceriu commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +    var isSyncing: Bool {
Oh okay, got it 👍

2023-05-19 08:14 UTC, stefanceriu commented
> instead with it it gets sent in bg

Huh, interesting, okay then 👍

2023-05-19 08:14 UTC, stefanceriu approved these changes

2023-05-19 08:15 UTC, Velin92 commented on ElementX/Sources/Services/Client/ClientProxy.swift
> +    var isSyncing: Bool {
but you know what, let me replace these slidingSyncObserverToken == nil internally with the isSyncing check, so it's a tad bit cleaner

2023-05-19 08:28 UTC, merged